### ISSUE TITLE
Lyft

### ISSUE THREAD

**Issue by dkhamsing** [brandcolors/feedback#150]
https://www.lyft.com
#00B4AE

**Comment by galengidman** [comment]
Published.

**Comment by RisingSkylar** [comment]
Lyft's style guide has a lot more colors listed.

#ea0b8c
#fcdcf0
#585551
#c2bcb5
#85a6c7
#00b2a9
#9bd9d9

https://www.lyft.com/style

**Comment by dkhamsing** [comment]
Will update
Thanks

**Comment by dkhamsing** [comment]
Uh actually will need @galengidman's help on this.. can u reopen this issue if you want to do this later?

**Comment by galengidman** [comment]
Thanks for pointing that out RisingSkylar. Updated.
