### ISSUE TITLE
3 letter hex codes issues in some software

### ISSUE THREAD

**Issue by panev** [brandcolors/feedback#193]
Some graphic editing software, most notably Adobe Illustrator, do not work well with 3 letter hex codes. For example, instead of duplicating the RGB values of f80 into ff8800, like Photoshop does, Illustrator in particular turns it into 000f80. 

Hardly an issue, but its a bit of a nuisance. Perhaps there can be a little tick mark to switch between 3/6 letter hex codes or something?

**Comment by galengidman** [comment]
This has been fixed.
