### ISSUE TITLE
500px

### ISSUE THREAD

**Issue by jeff-shin** [brandcolors/feedback#205]
Wanted to update 500px's brand colours (I'm a designer at 500px).

Blue - #0099e5
Red - #ff4c4c
Green - #34bf49

Cheers.

**Comment by galengidman** [comment]
Thanks, added!

**Comment by spotimodyapk** [comment]
Welcome to **spotimody.app** your one-stop destination for the best music streaming app with premium features unlocked. If you’re a music lover who wants access to millions of songs, playlists, and podcasts without limitations, then you’ve come to the right place. Here, we’ll introduce you to the [Spotify ](https://spotimody.app/)MOD APK, a modified version of the popular Spotify app that offers all premium features for free. Let’s dive in and explore everything this amazing app has to offer!

What is Spotify MOD APK?
Spotify MOD APK is a modified version of the official Spotify app. It is designed to give users access to premium features without requiring a subscription. With this APK, you can enjoy ad-free music streaming, unlimited skips, offline downloads, and high-quality audio – all for free! Whether you’re into pop, rock, jazz, or podcasts, Spotify MOD APK has something for everyone.
