### ISSUE TITLE
Request: Copy Hex Color to Clipboard on Click

### ISSUE THREAD

**Issue by calebsylvest** [brandcolors/feedback#216]
Currently when you click a color block the block expands to present the hex code. Can you upgrade so when you click you also automatically copy the hex code to the clipboard?

![screen shot 2014-12-16 at 10 22 51 am](https://cloud.githubusercontent.com/assets/4457883/5457045/82946a74-850d-11e4-815a-b8216d15de5d.png)

**Comment by galengidman** [comment]
I'd love to add this, but the *only* way to setup copy to clipboard is to use Flash and that really hurts performance.
