### ISSUE TITLE
American Red Cross

### ISSUE THREAD

**Issue by csaper** [brandcolors/feedback#224]
#### Primary Colors
#FFFFFF
#6D6E70
#ED1B2E

#### Neutral Colors
#D7D7D8
#9F9FA3
#000000

#### Secondary Colors
#E2D7AC
#B4A996
#ECB731
#8EC06C
#537B35
#C4DFF6
#56A0D3
#0091CD
#004B79
#7F181B

*Source: American Red Cross Brand Guidelines*

**Comment by galengidman** [comment]
Added, thanks!
