### ISSUE TITLE
Click to copy hex to clipboard

### ISSUE THREAD

**Issue by dvointeractive** [brandcolors/feedback#24]
As an interaction designer, I was hoping that clicking on one of these would copy the hex value to my clipboard.

Presumably, those who need/want the hex value of these brand colors want to use them somewhere. I'm sure it would be a welcomed interaction to quickly copy to your clipboard - like bitly allows when you create a new bitmark.

I'd recommend zclip: http://www.steamdev.com/zclip/

**Comment by dyaa** [comment]
Now i could be easier and better without using flash https://github.com/zenorocha/clipboard.js/

I can help you doing it if you dont have enough time.

**Comment by galengidman** [comment]
Closing this - live as of the current version launched last month.
