### ISSUE TITLE
PayPal

### ISSUE THREAD

**Issue by csaper** [brandcolors/feedback#243]
#### Primary Palette
#00457C
#0079C1
#FFFFFF
#000000

#### Neutral Palette
#959484
#E7E5D3
#717074
#E6E7E8

#### Accent Palette
#6DB33F
#C2CD23
#007C85
#26BCD7
#B32317
#F8981D
#7A003C
#F15F7C

*Source: PayPal Corporate Master Brand Guidelines*

**Comment by galengidman** [comment]
Thanks for this, but I got a few more recent codes from the designer of their new brand recently.
