### ISSUE TITLE
Delectable

### ISSUE THREAD

**Issue by bearroast** [brandcolors/feedback#245]
**Primary**
#334858
#CD595A

**Secondary**
#94938F
#A3A7A6
#DBC5B0
#F8DFC2
#F9EBDF

https://itunes.apple.com/us/app/delectable-wines-wine-scanner/id512106648?mt=8
https://play.google.com/store/apps/details?id=com.delectable.mobile&hl=en

**Comment by galengidman** [comment]
Added.
