### ISSUE TITLE
Unity3D Website colors

### ISSUE THREAD

**Issue by LeonHaker** [brandcolors/feedback#251]
Can you post colors of http://unity3d.com/ ?

**Comment by dkhamsing** [comment]
Will submit it.. 

@galengidman I think the admin panel is down
19E3B1

**Comment by galengidman** [comment]
Fixed `wp-admin/`

**Comment by dkhamsing** [comment]
Thx
Submitted

**Comment by galengidman** [comment]
Updated with colors found here: http://unity3d.com/public-relations/brand
