### ISSUE TITLE
SocialBro colors

### ISSUE THREAD

**Issue by angelcreative** [brandcolors/feedback#254]
Our main colors are:

#29c4d0 #f29556 #84afa2 #72c427 #f24c7c #00aaf2

Plus, we have all this set of colors:

![image](https://cloud.githubusercontent.com/assets/3775982/6616951/d7e6b36c-c8b3-11e4-9fc1-f0c9104b039c.png)

**Comment by dkhamsing** [comment]
Submitted for review, thank you

**Comment by galengidman** [comment]
Published, thank you both.
