### ISSUE TITLE
NBC

### ISSUE THREAD

**Issue by pjtothestars** [brandcolors/feedback#255]
Hello, I work for an NBC TV affiliate and would like to submit the network's peacock colours to the site:

Yellow: E1AC26
Orange: DC380F
Red: 9F0812
Purple: 6347B2
Blue: 368DD5
Green: 70AF1E
Grey: 7E887A

Source:
https://www.dropbox.com/s/u48s03bhym220db/NBC_PEACOCK_USERGUIDE.PDF?dl=0

**Comment by dkhamsing** [comment]
Will submit it, thx

**Comment by dkhamsing** [comment]
Submitted for review, thank you

**Comment by galengidman** [comment]
Published, thank you both!
