### ISSUE TITLE
Brand colors for Roo Kids

### ISSUE THREAD

**Issue by ddiinnxx** [brandcolors/feedback#256]
Please add brand colors for Roo Kids (http://www.RooKidsApp.com). You need not verify the colors. I am the founder :)

#E22027
#A1CD3D
#003E70

![roo-kids-80x80](https://cloud.githubusercontent.com/assets/3467396/6817544/d994a9c6-d2c7-11e4-95e7-6dd65eee4525.png)

![roo-kids-400x160](https://cloud.githubusercontent.com/assets/3467396/6817560/0b0adef8-d2c8-11e4-9aba-a57ec90c43ae.png)

**Comment by dkhamsing** [comment]
Submitted for review

**Comment by galengidman** [comment]
Thanks guys, published.
