### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by kutec** [brandcolors/feedback#258]
Hey I have created a jQuery plugin for WhatsApp and at that time I was searching for color code for the icon but couldn't find on your brandcolors.net. Adding it will be beneficiary for the community.

**Comment by dkhamsing** [comment]
Submitted 64D475 for review

**Comment by copperdesign** [comment]
The color on WhatsApp's Site is #4DC247

**Comment by dkhamsing** [comment]
@copperdesign thanks, updated with 4DC247
It is pending review

**Comment by galengidman** [comment]
Published.
