### ISSUE TITLE
Identi.ca

### ISSUE THREAD

**Issue by BWPanda** [brandcolors/feedback#260]
Identi.ca colors:
Green: #789240
Red: #7d0100
Blue: #8baaff

From: http://en.wikipedia.org/wiki/File:Identi.ca_logo_svg.svg

**Comment by dkhamsing** [comment]
Hmm

http://en.wikipedia.org/wiki/Identi.ca
>  Identi.ca stopped accepting new registrations in 2013, but continues to operate alongside several other pump.io-based hosts provided by E14N which continue to accept new registrations

**Comment by BWPanda** [comment]
Yeah, they're not really around anymore, but the alternatives (pump.io, status.net, GNUsocial) don't have a standard social icon so Identi.ca's is still used.

**Comment by dkhamsing** [comment]
I see, will submit it later

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published.
