### ISSUE TITLE
[Brand Update] Yo - In regards to Issue #151

### ISSUE THREAD

**Issue by bohl3r** [brandcolors/feedback#276]
I've been peaking around at Yo due to their simplicity and ease to developers. With this, I've browsed their docs and noticed a conflict with the current brand color on the site.

You could say that the purple (which is currently the only color) is correct as far as their main representation, although their application itself includes all of the colors listed below.

Here are the following color codes of their application as noted by their developer docs located at http://docs.justyo.co/v1.0/docs/ui-design-guidelines

TURQUOISE - #1ABC9C - blueish green
EMERALD - #2ECC71 - 	light green
PETER - #3498DB - light blue
ASPHALT - #34495E - dark blue
GREEN - #16A085 - green
SUNFLOWER - #F1C40F - orange yellow
BELIZE - #2980B9 - blue
WISTERIA - #8E44AD - dark purple
ALIZARIN - #e74c3c - red (menu button)
AMETHYST - #9B59B6 - the main purple

**Comment by dkhamsing** [comment]
@galengidman check this out

**Comment by galengidman** [comment]
Thanks guys, updated Yo with the additional colors. On a humorous note, their "brand" is just pulled directly from here: http://flatuicolors.com/

**Comment by dkhamsing** [comment]
haha sounds about right
