### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by oxyberg** [brandcolors/feedback#286]
`#0088cc`, `#e0d8cb` at [Telegram](http://telegram.org)

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
`#0088cc` looks right, but I'm not sure I'd call `#e0d8cb` a brand color. Do you work for them?

**Comment by oxyberg** [comment]
@galengidman Nope, but it is the secondary color on the site.

**Comment by CosmoMyzrailGorynych** [comment]
`#0088cc` is just for links on the site and no more. There are really many other shades all over the telegram's site (I've counted 10 of such and gave up). But the color which associates with Telegram is a more brighter one.

If we look into an [official logo](https://telegram.org/press#telegram-logos), we will find a 2-color gradient:

* `#38b0e3` — top;
* `#1d93d2` — bottom.

This icon is shown at telegram's chat [(image)](https://cloud.githubusercontent.com/assets/3174357/17505250/1199248c-5e54-11e6-81a4-99afd281033b.png), as an icon for MacOS and as mobile apps' icons,

There is also a flat icon which is shown in [Telegram Web](https://web.telegram.org/) and as an icon for Windows app. The color of [such icon](https://desktop.telegram.org/) icon is `#2ca5e0`. This one lies in the gradient's band somewhere at position 0.4 (+- 0.02).

So I propose `#2ca5e0` to be a Telegram's brand color, and maybe `#38b0e3` and `#1d93d2`.

There is also a `#27A5E7`, favico color (https://telegram.org/favicon.ico?3), but it hardly lies in the gradient's band.

**Comment by galengidman** [comment]
Published long ago — closing.
