### ISSUE TITLE
StubHub

### ISSUE THREAD

**Issue by efremidze** [brandcolors/feedback#288]
`#004b91` and `#ff7300` at StubHub

**Comment by dkhamsing** [comment]
Thanks, it was submitted for review.

**Comment by efremidze** [comment]
If you inspect the stubhub logo on the stubhub website, you can see the fill they are using for the logo.
`<path fill="#004B91"></path><path fill="#FF7300"></path>`

**Comment by dkhamsing** [comment]
:+1:

**Comment by galengidman** [comment]
Published, thanks!
