### ISSUE TITLE
Website Feedback: Add json download

### ISSUE THREAD

**Issue by jasonbaddley** [brandcolors/feedback#291]
It would be fantastic to be able to download a json file of these colors something like:

{
   "4ormat":["#fb0a2a"],
   "500px":["#0099e5","#ff4c4c","#34bf49"]
 
   ....

}

This would very much help a lot of people who need to programmatically control brand colors in their website.

**Comment by galengidman** [comment]
http://brandcolors.net/api/v1/

This isn't a heavily publicized feature and I'd recommend against building anything that calls it directly, but it sounds like you just want to download the data anyway.
