### ISSUE TITLE
UC Berkley

### ISSUE THREAD

**Issue by MitchellGeere** [brandcolors/feedback#293]
University of California, Berkley

Primary Palettes
#041e42
#ffc72c
#4f758b
#d19000

http://brand.berkeley.edu/colors/

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by dkhamsing** [comment]
You misspelled `Berkeley` :grin:

**Comment by MitchellGeere** [comment]
ha ha whoops! :)

**Comment by galengidman** [comment]
Added, thanks!
