### ISSUE TITLE
[Brand Update] Starbucks

### ISSUE THREAD

**Issue by bohl3r** [brandcolors/feedback#295]
Current color is #00704a, which is slightly off to the color that I discovered in the logo and on the site's cs which is #006241. Also to note, black is not apart of their brand at all; but white can be added due to its affiliation in the logo.

Site:
http://starbucks.com

Logo Download:
http://www.starbucks.com/static/images/logo.png

**Comment by dkhamsing** [comment]
Thanks
@galengidman will take care of it

**Comment by galengidman** [comment]
According to this brand guidelines document, it's correct: http://starbucksocs.com/pdf/WPSlogoGuidelines.pdf
