### ISSUE TITLE
WOSM (World Organisation of the Scout Movement)

### ISSUE THREAD

**Issue by sebastien-bartoli** [brandcolors/feedback#296]
Brand colors are purple and white.

Purple : `#622599` | Pantone 527 C
White : `#FFFFFF`

From there : [Brand Manual](http://scout.org/sites/default/files/library_files/Brand%20Manual_EN.pdf)

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published, thanks!
