### ISSUE TITLE
[Update] Pocket

### ISSUE THREAD

**Issue by mbignell** [brandcolors/feedback#297]
Hey! Lovely site. I'm a designer at Pocket and just wanted to give you our exact brand colors, as they differ a bit from what's live.

The red — #EF4056
The teal — #50BCB6

Thanks for the work in collecting these! Awesome resource.

**Comment by dkhamsing** [comment]
Thanks
Paging @galengidman

**Comment by galengidman** [comment]
Updated. Thanks!
