### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by yuripertamax** [brandcolors/feedback#307]
I'm not sure but maybe this will help.
[Sublime Text](http://www.sublimetext.com/) — `#FF8100`, `#4C4C4C`, and `#262626`
color taken from flat image of sublime text logo [here](http://minimaldev.com/img/sublime_text_icon.svg)

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Hmm, I appreciate you sending this in, but since those colors are taken from an unofficial source, I'm going to pass on them for now. Hopefully we'll be able to find something more official down the road.
