### ISSUE TITLE
Codepen

### ISSUE THREAD

**Issue by wolf-w** [brandcolors/feedback#310]
`#B90C0C`, `#66CE5B`, `#40DBE5`, `#D75E5E`, `#A561CB`, `#D4A12C` and finally `#F37A29` - got it from http://codepen.io/guide/

Nice work!! c:

**Comment by dkhamsing** [comment]
Hmm

> We don't really have a "brand" color, other than the general concept of light-on-dark.

**Comment by wolf-w** [comment]
Yes, but they have some colors to use..
I know what you mean but i think you could add this colors x.x

Am 24.06.2015 um 00:13 schrieb dkhamsing:

**Comment by galengidman** [comment]
Published.

**Comment by theLMGN** [comment]
Shouldn't the logo's black and white be included. (even if it's just #fff and #000)

**Comment by galengidman** [comment]
I feel pretty good about where we're at with this.
