### ISSUE TITLE
Website Feedback: Add PMS and CMYK

### ISSUE THREAD

**Issue by Revod** [brandcolors/feedback#313]
Hey, thanks for you great project, love it. What is the possibility to update the Brand colors and add the PMS color and the CMYK Colors?

**Comment by dkhamsing** [comment]
Submit updates or additions here, we'll take a look :smile:

**Comment by galengidman** [comment]
In a word, no. It's much easier to find screen colors for brand than print colors. Possibly down the road, we'll setup functionality for adding print colors to new brands if we can find them, but I don't see us ever going top to bottom and adding print colors for what's already there. Unless of course you want to make that your life mission for the next couple of weeks. :stuck_out_tongue_closed_eyes:
