### ISSUE TITLE
Website Feedback: Hover Effect for Colors

### ISSUE THREAD

**Issue by n8maninger** [brandcolors/feedback#314]
The hover effect:

``` css
.color .color-inner:hover {
    position: absolute;
    right: 10px;
    left: 10px;
    z-index: 1;
```

Is kind of off putting as it requires me to leave the row entirely to see the brand's other colors.

**Comment by galengidman** [comment]
Do you have any ideas for a more user-friendly interaction? I'm all ears.

**Comment by tvsloot** [comment]
Can you not simply show the hex over the individual color column on hover instead of taking over the whole row? You would lose no functionality and it would be easier for the user to navigate.

**Comment by galengidman** [comment]
That would work great for brands with one or just a few colors, but what about brands that have a bunch of colors?

**Comment by n8maninger** [comment]
You could push the other brands into smaller boxes and center the hovered one. That would give a similar effect and allow color switching.

**Comment by galengidman** [comment]
Hmm, I like that. A lot actually. Can't promise when, but I'll work on this. Thanks for the feedback.

**Comment by matthew-dean** [comment]
I actually dislike both versions, as pushing the boxes makes the box positions unpredictable, as you move the mouse around the page. It's almost the same problem, just slightly not as much of a problem.

IMO the two better solutions are:

1) Use tooltips - that way colors don't jump around the page, and you have as much room as you need. However, that doesn't work well for mobile, so...
2) Just put a list of color values under the row of colors, in the same order. Sometimes simplest is best. That would also work better for mobile, where you could make a smaller row of color squares, followed by a list of values.

**Comment by galengidman** [comment]
Closing this - no longer an issue with the current version of the site.
