### ISSUE TITLE
Vodafone

### ISSUE THREAD

**Issue by megankreuz** [brandcolors/feedback#316]
Vodafone red: #E60000
Vodafone white: #FFFFFF
Vodafone grey: #4A4E4D

sourced from their brand guidelines: pg.6
http://www.webguruafrica.com/vodacom-rhombus-ci/Vodafone%20Digital%20Guidelines%20FINAL%2014.8.13.pdf

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published, thanks!
