### ISSUE TITLE
MercadoLibre

### ISSUE THREAD

**Issue by battaglr** [brandcolors/feedback#317]
[MercadoLibre](https://en.wikipedia.org/wiki/MercadoLibre.com) brand colors:
- Yellow: `#ffe600`
- Blue: `#2d3277`

The colors are from the official brand manual —which I'm not sure I can share here. Let me know if you need anything else.

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published, thanks!
