### ISSUE TITLE
NC State University

### ISSUE THREAD

**Issue by swarmingzebras** [brandcolors/feedback#318]
Main Colours
Red: #cc0000
Black: #000000
White: #ffffff 

Expanded Palette
Red: #990000
Orange:  #d14905
Yellow: #fdd726
Green: #7d8c1f
Blue: #427e93
Indigo: #4156a1

From: http://brand.ncsu.edu/color/

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published.
