### ISSUE TITLE
New Lyft Colors

### ISSUE THREAD

**Issue by RisingSkylar** [brandcolors/feedback#329]
I think I was able to snag Lyft's entire new color pallet from their New Year, New Lyft series on YouTube. https://www.youtube.com/watch?v=162DW2NaB0g&t=8s

![lyft palette](https://cloud.githubusercontent.com/assets/8880128/9005565/e3046e9c-3744-11e5-9f3c-3bdceb6c26bf.png)

The video is from January, so it's sad to me that it took so long for me to catch that the pallet was in the video.

I went ahead and dug into Lyft's CSS and was able to pull the following colors: 

#00B2A9 - Green+
#9BD9D9 - Green-mint+
#585551 - Gray+
#333 - Gray-dark+
#222 - Gray-darker+
#C2BCB5 - Gray-light+
#F1F2F2 - Gray-lighter+
#2AACE3 - Blue+
#FFFFFF - White*
#EA0B8C - Pink*
#333D47 - Charcoal*
#7D9AA7 - Frost*
#B1C2CA - Fog*
#D8DFE6 - Moonstone*
#F3F5F5 - Snow*
#AE005E - Reddish*
#FAA33B - Orangeish*
#FCEE22 - Yellowish*
#33D9C2 - Greenish*
#2AACE3 - Blueish*
#FCDCF0 - Pink-blush*

I was able to go back through their old CSS thanks to the Internet archive and find the ol' shade of pink: #ED627B

+Original Lyft Colors
*New Lyft Colors

I'm not sure how you guys want to update their colors, but I'm 98% sure that the ones with the astriks are current, and much more useful than the other colors.

**Comment by dkhamsing** [comment]
@galengidman will have to take a look
Thanks

**Comment by galengidman** [comment]
Hmm, thanks for digging this up. I've narrowed this list a bit and published.
