### ISSUE TITLE
Highfive Branding

### ISSUE THREAD

**Issue by mirshko** [brandcolors/feedback#331]
Primary: #A26EEA
Secondary: #F7AFFF
Tertiary: #5C70EA
Quaternary: #46B7FD
Text Color: #27292B

https://highfive.com/contact

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by IFSTREAM** [comment]
Sure thing

**Comment by galengidman** [comment]
Published, thanks.
