### ISSUE TITLE
Zapier Colors

### ISSUE THREAD

**Issue by smbriones** [brandcolors/feedback#332]
Love this! :heart: 

Here are Zapier's (https://zapier.com/) brand colors:

#FF4A00
#FD7622
#FFC43E
#5F6C72
#499DF3
#13D0AB

Cheers!

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Thanks, published.

**Comment by smbriones** [comment]
Thanks, @galengidman! :smile:
