### ISSUE TITLE
Database error when trying to download collection

### ISSUE THREAD

**Issue by adrian7** [brandcolors/feedback#335]
Error establishing a database connection
e.g. http://brandcolors.net/download/?brands=28,29&format=css

**Comment by dkhamsing** [comment]
Paging @galengidman

**Comment by galengidman** [comment]
Aware of this guys. Not sure what the issue is but I will investigate.

**Comment by galengidman** [comment]
This has been fixed.

**Comment by dkhamsing** [comment]
Thanks
