### ISSUE TITLE
Whatsapp Web Colors

### ISSUE THREAD

**Issue by FerdiCildiz** [brandcolors/feedback#340]
#009888
#1d8d83
#2b978b
#59ee6a
#f7f9fa
#57c4f9
#777777
#4ef462
![untitled-1](https://cloud.githubusercontent.com/assets/6659325/9466680/4d11a666-4b3f-11e5-9d6c-706dce18e35c.jpg)

**Comment by dkhamsing** [comment]
@galengidman will have to update this

**Comment by galengidman** [comment]
Thanks submitting @FerdiCildiz. For now I'm going to stick with just the green unless I can see some kind of official style or identity guidelines. If you happen to run across something like that, please let me know!
