### ISSUE TITLE
Onshape Branding

### ISSUE THREAD

**Issue by mirshko** [brandcolors/feedback#342]
## Primary Color Palette
#1B5FAA (Primary Blue)
#90CEF1 (Cloud)
#FFC20E (Gold)

## Secondary Color Palette
#002847 (Navy)
#DD5228 (Red)
#606A73 (Steel)
#9AA5AF (Aluminum)
#CFDBE5 (Titanium)
#D9C1DD (Pink)

## Source
I also work here, I made the internal branding page (Here is screenshot of that, cannot provide public link)

![brand colors](https://cloud.githubusercontent.com/assets/8116716/9496755/edeba974-4bdf-11e5-965a-92ad84b4c959.png)

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
