### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by dkhamsing** [brandcolors/feedback#343]
Same as #335 ?

**Comment by galengidman** [comment]
Probably. I'm not sure what the issue is. Unmanaged virtual servers are great until they're not and you're not a sysadmin. I'll take a look and see if I can figure something out.

**Comment by dkhamsing** [comment]
Thx

**Comment by dkhamsing** [comment]
Huh so weird, works on my iPhone and in Safari.. but get this error in Chrome

**Comment by galengidman** [comment]
Fixed again for now. For some reason MySQL keeps running out of memory. Let me know if pops up again.

**Comment by dkhamsing** [comment]
For sure
