### ISSUE TITLE
Direct Energy

### ISSUE THREAD

**Issue by nerdydeeds** [brandcolors/feedback#344]
Orange: #f05d21
Blue: #939598
Green: #0f723a
Light Grey: #c7c8ca
Grey: #666666

How I know: I'm a designer for Direct Energy Business based in Pittsburgh, PA.

**Comment by dkhamsing** [comment]
Hi, `939598` is gray, I replaced it with `005776`

Submitted for review

**Comment by nerdydeeds** [comment]
Blue for Direct Energy Business has been updated to #2c5770 and I think that Direct Energy Residential might follow suit. 

Good catch - not sure where that grey came from. Probably my pasteboard lol

**Comment by dkhamsing** [comment]
Updated to use 2c5770, thanks

It has been submitted for review

**Comment by galengidman** [comment]
Published, thanks.
