### ISSUE TITLE
Cartoon Network - Check It

### ISSUE THREAD

**Issue by bgiesing** [brandcolors/feedback#347]
https://color.adobe.com/Cartoon-Network-Check-It-color-theme-6815491/

## Color Codes
```
#ED0B91
#00B3F2
#F0E502
#F3F3F3
#0C0D10
```

EDIT: Colors from this official brand image:
![cn-check-it-web](http://vignette3.wikia.nocookie.net/cartoonnetwork/images/5/5d/Cn-2014-brand-bg.png/revision/latest?cb=20140416000203)

**Comment by dkhamsing** [comment]
Submitted for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
