### ISSUE TITLE
Apple old colors

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#353]
(adobe colors)

Green: 61bb46

Yellow: fdb827

Orange: f5821f

Red: e03a3e

Purple: 963d97

Blue: 009ddc

**Comment by galengidman** [comment]
Are these Apple's colors or Adobe's colors?

**Comment by riay388** [comment]
Hi,

It's from a vector I downloaded from the web with the old logo colors.



On Mon, Oct 12, 2015 at 12:41 PM, Galen Gidman <notifications@github.com>
wrote:

> Are these Apple's colors or Adobe's colors?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandcolors/feedback/issues/353#issuecomment-147500824>
> .
>



-- 

~Yair Davidowitz

**Comment by riay388** [comment]
It's from wikipedia, actually.

On Mon, Oct 12, 2015 at 12:54 PM, Yair Davidowitz <yair.david0@gmail.com>
wrote:

> Hi,
>
> It's from a vector I downloaded from the web with the old logo colors.
>
>
>
> On Mon, Oct 12, 2015 at 12:41 PM, Galen Gidman <notifications@github.com>
> wrote:
>
>> Are these Apple's colors or Adobe's colors?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brandcolors/feedback/issues/353#issuecomment-147500824>
>> .
>>
>
>
>
> --
>
> ~Yair Davidowitz
>



-- 

~Yair Davidowitz

**Comment by riay388** [comment]
I cannot find it on the official apple website, as it is really old (1998).

On Mon, Oct 12, 2015 at 12:55 PM, Yair Davidowitz <yair.david0@gmail.com>
wrote:

> It's from wikipedia, actually.
>
> On Mon, Oct 12, 2015 at 12:54 PM, Yair Davidowitz <yair.david0@gmail.com>
> wrote:
>
>> Hi,
>>
>> It's from a vector I downloaded from the web with the old logo colors.
>>
>>
>>
>> On Mon, Oct 12, 2015 at 12:41 PM, Galen Gidman <notifications@github.com>
>> wrote:
>>
>>> Are these Apple's colors or Adobe's colors?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/brandcolors/feedback/issues/353#issuecomment-147500824>
>>> .
>>>
>>
>>
>>
>> --
>>
>> ~Yair Davidowitz
>>
>
>
>
> --
>
> ~Yair Davidowitz
>



-- 

~Yair Davidowitz

**Comment by dkhamsing** [comment]
Galen I think this is the logo in question

![150401_apple_logo](https://cloud.githubusercontent.com/assets/4723115/10437398/94f56cca-70e1-11e5-9513-423451a3471e.png)

**Comment by galengidman** [comment]
Thanks for the clarifications. I wondered since you started your OP with "(adobe colors)".

I think I'm going to pass on these since they're no longer active. Thanks for sending them in though.

**Comment by riay388** [comment]
Other people may want it though, just saying.

On Mon, Oct 12, 2015 at 1:05 PM, Galen Gidman <notifications@github.com>
wrote:

> Closed #353 <https://github.com/brandcolors/feedback/issues/353>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brandcolors/feedback/issues/353#event-433315916>.
>



-- 

~Yair Davidowitz
