### ISSUE TITLE
McDonald’s Color Palette

### ISSUE THREAD

**Issue by matthijs110** [brandcolors/feedback#354]
Here are the 3 colors of McDonalds.

* McDonald's Red
  * HEX: **#dd1021**
  * RGB: **221**, **16**, **33**
* McDonald's Yellow:
  * HEX: **#ffc300**
  * RGB: **255**, **195**, **0**
* McDonald's white:
  * HEX: **#fff**
  * RGB: **255*, **255**, **255**

[**Source**](http://designpieces.com/palette/mcdonalds-color-palette/)

**Comment by dkhamsing** [comment]
Thanks, submitted for review

**Comment by galengidman** [comment]
Thanks, published.
