### ISSUE TITLE
Zapier

### ISSUE THREAD

**Issue by runningskull** [brandcolors/feedback#355]
Color: `#FF4A00` (bright orange)

Source: [zapier brand guidelines](https://zapier.com/about/brand/)

**Comment by dkhamsing** [comment]
Dupe #332

**Comment by runningskull** [comment]
@dkhamsing - thanks, not sure how i missed that.

**Comment by dkhamsing** [comment]
@runningskull oh we are in the process of adding it.. thanks :smile:

**Comment by galengidman** [comment]
Published, thanks.
