### ISSUE TITLE
Apricot colors

### ISSUE THREAD

**Issue by LasseRafn** [brandcolors/feedback#356]
I run a startup\* called "Apricot" - with the main colours:

Orange: 
-    #F2A649

Greens:
-    #74BF3A
-    #7AC943

Logo for reference:
![apricot](https://cloud.githubusercontent.com/assets/2689341/10413520/52221852-6fac-11e5-9dce-678d32b78b81.png)

*So it may not fit into the category "worlds biggest brands".. Well, not yet. Now you have it, add it or not. 

I like the project, keep it up! I can finally stop going to ColourLovers for reference anymore.

**Comment by galengidman** [comment]
Is it live yet?
