### ISSUE TITLE
Fedex Purple

### ISSUE THREAD

**Issue by kestrelprodigal** [brandcolors/feedback#359]
Fedex Purple should be 4d148c instead of 660099

**Comment by dkhamsing** [comment]
Thanks
Paging @galengidman

**Comment by galengidman** [comment]
Not according to their identity guidelines: https://fabiosardinha.files.wordpress.com/2008/01/fedex_guidelines.pdf

What makes you think `#609` is incorrect?

**Comment by kestrelprodigal** [comment]
That is their old purple color from what I remember, they have since updated. If you take a look at their site you will see that just about every page should be using #4d148c for the headlines and link colors as well as various other things.  (I work as a developer for Tank Design whose main client is FedEx, so we use it everyday)

**Comment by galengidman** [comment]
Gotcha. Will update. Also, if you happen to have access to an updated copy of their identity guidelines, I'd love to update the rest of their colors as well.
