### ISSUE TITLE
HomeAway

### ISSUE THREAD

**Issue by PaddyMurphy** [brandcolors/feedback#361]
HomeAway blue: #2a6ebb
HomeAway orange:  #f0ad4e

**Comment by dkhamsing** [comment]
Submitted brand `907` for review, thanks

**Comment by galengidman** [comment]
The orange looks pretty light to me. Where did you get these?

**Comment by PaddyMurphy** [comment]
oh, good catch that is one of the tints. The correct orange is #ff8a00. Taken from the HomeAway styleguide. (You can also sample it from the homeaway.com search button)

**Comment by galengidman** [comment]
Published, thanks.
