### ISSUE TITLE
Duolingo

### ISSUE THREAD

**Issue by ioana-chiorean** [brandcolors/feedback#362]
I would like to suggest to add Duolingo: https://www.duolingo.com/

**Comment by dkhamsing** [comment]
Thanks, can you find the brand color :grin:

**Comment by ioana-chiorean** [comment]
Yes.
#76C641
#6EB039
#DA832F
#8CDD4B
#FFC045
//sorry for the delay, i though i replied here..

**Comment by dkhamsing** [comment]
Submitted brand `1345` for review, thanks

**Comment by galengidman** [comment]
@ioana-chiorean Where were these sourced from?

**Comment by ioana-chiorean** [comment]
@galengidman at this point I do not remember honestly speaking. There were 2 scenarios triesȘ
- researched their page/logo
- used the color picker to see them in the logo.

**Comment by galengidman** [comment]
Published.

**Comment by ioana-chiorean** [comment]
🎉
