### ISSUE TITLE
Webmaker tool

### ISSUE THREAD

**Issue by ioana-chiorean** [brandcolors/feedback#367]
Hey , I would like to propose for addition Mozilla's Webmaker tool: https://www.mozilla.org/en-US/styleguide/identity/webmaker/branding/
Android app: https://play.google.com/store/apps/details?id=org.mozilla.webmaker

**Comment by galengidman** [comment]
This seems to be the exact same color scheme as Mozilla itself, no?

**Comment by ioana-chiorean** [comment]
Yes.
//sorry for the delay, i though i replied here..

**Comment by ioana-chiorean** [comment]
Thank you! :bowing_woman:
