### ISSUE TITLE
Telegram forwarding bug?

### ISSUE THREAD

**Issue by megan657** [brandcolors/feedback#370]
Recently I have come across an unusual privacy problem in telegram, when you forward something to another group it randomly chooses one of your private messages and forwards that instead.This is a huge security problem and it has occured vai phone and PC For 3 people I know. Is this a bug?or a virus and where exactly is the problem?

**Comment by dkhamsing** [comment]
Uh please report this to the telegram project https://telegram.org/

**Comment by megan657** [comment]
Ok I will
