### ISSUE TITLE
NS (Nederlandse Spoorwegen)

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#371]
colors

[#ffac2a]
[#00337f]
[#ffffff]

![palette](https://cloud.githubusercontent.com/assets/5757371/11016611/b21aa4c4-8544-11e5-870b-37d6cba7f3a4.png)

Source: http://www.ns.nl/binaries/content/assets/NS/over-ns/nieuwscentrum%5B4%5D/dossiers/toolkit-rsb_versie-2.0_december-2012.pdf

**Comment by klombomb** [comment]
:+1:  goed idee

**Comment by dkhamsing** [comment]
Submitted brand `1019` for review, thanks

**Comment by galengidman** [comment]
Published, thanks!
