### ISSUE TITLE
frog design

### ISSUE THREAD

**Issue by JASKNi** [brandcolors/feedback#372]
**Primary Colors**
#339CE2, #299F55, #FFDE1A, #F58300, #DE3E1C

**Reseved Colors**
#000000, #FFFFFF, #46BD00

**Comment by dkhamsing** [comment]
Adding `46BD00` only..
Submitted brand `1018` for review, thanks

**Comment by galengidman** [comment]
Since you guys seem to be more of an agency rather than a brand or service, I'm going to decline this submission. I realize that we currently have thoughtbot on the site which is also a design agency, so I'm removing them as well. Thanks for contributing!
