### ISSUE TITLE
Youtube Updated 

### ISSUE THREAD

**Issue by klombomb** [brandcolors/feedback#373]
https://www.youtube.com/yt/brand/en/color.html
You can find them all hear! ^^^^^

**Comment by dkhamsing** [comment]
Thanks, @galengidman will take care of it

**Comment by galengidman** [comment]
The current color is correct per that document. Thanks for submitting though.

**Comment by klombomb** [comment]
Okay! They seem to switching to the newer more deimensional red though!

**Comment by galengidman** [comment]
By dimensional do you mean the gradient? That may be, but we don't post gradients on BrandColors. Solid colors only.
