### ISSUE TITLE
University of Arizona

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#378]
Blue: Pantone 281; rgb: 0, 51, 102;  hex: 003366
Red: Pantone 200; rgb: 204, 0, 51;  hex: cc0033

Source: http://licensing.arizona.edu/sites/licensing/files/ua_id_guide_0.pdf

**Comment by dkhamsing** [comment]
Submitted brand `1106` for review, thanks

**Comment by galengidman** [comment]
Published.
