### ISSUE TITLE
Add React

### ISSUE THREAD

**Issue by kentcdodds** [brandcolors/feedback#380]
Maybe @vjeux knows what the hex values for the React colors are. But if you've got Ember and Angular on here you've totally gotta have React too! :D

**Comment by kentcdodds** [comment]
For what it's worth, on [the React homepage](https://facebook.github.io/react/), the hex for the title is `#61dafb`

**Comment by dkhamsing** [comment]
Submitted brand `1116` for review, thanks

**Comment by galengidman** [comment]
Grabbed `#00d8ff` from the logo. https://facebook.github.io/react/img/logo.svg

Published, thanks!

**Comment by kentcdodds** [comment]
Fantastic. Thanks! :D
