### ISSUE TITLE
Bombardier

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#381]
Pantone 7544 C --> 8996a0
Pantone 7545 Uncoated
Pantone Black--> 000000

Source: http://www.bombardier.com/content/dam/Websites/bombardiercom/supporting-documents/BInc/BI-EoM_BrandGuidelines_at_a_Glance-EN.pdf

**Comment by dkhamsing** [comment]
Adding `8996a0` only..
Submitted brand `1285` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
