### ISSUE TITLE
London Underground

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#384]
Coated:
Pantone 072C
Pantone 485C

Uncoated: 
PMS 072U
PMS 485U

Screen (RGB):
Blue: 0, 25, 168
Red: 220, 36, 31

Web:
000099
cc3333

Source: http://content.tfl.gov.uk/lu-basic-elements-standard1.pdf

**Comment by dkhamsing** [comment]
Submitted brand `1289` (added `web`) for review, thanks

FYI https://en.wikipedia.org/wiki/London_Underground
> The London Underground (also known as the Tube or simply the Underground)

**Comment by galengidman** [comment]
Published, thanks!
