### ISSUE TITLE
GVB

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#385]
Blue: PMS 300 >> 0863b5
Yellow: PMS 123 >> fec600
Orange: PMS 151 >> f39100
Red: PMS 032 >> e3001f
Pink: PMS 213 >> e50064
Purple: PMS 2582 >> 954a97
Cyan: PMS Process Cyan >> 009ee3
Green: PMS 361 >. 13a538

Source: http://assets.gvb.nl/kleuren-2015.pdf

**Comment by dkhamsing** [comment]
Submitted brand `1290` for review, thanks

**Comment by galengidman** [comment]
This was published March 30, 2016 and I forgot to close.
