### ISSUE TITLE
TYPO3

### ISSUE THREAD

**Issue by halbkreativ** [brandcolors/feedback#386]
The primary TYPO3 color is a friendly, bright orange:
> Orange: PANTONE Orange 021C |  RGB: 255/135/0 | Hex: #FF8700

Source: http://typo3.org/about/the-brand/style-guide/the-typo3-colors/

**Comment by dkhamsing** [comment]
Thanks @halbkreativ 
Paging @galengidman to update

**Comment by galengidman** [comment]
Updated, thanks!

**Comment by halbkreativ** [comment]
You're welcome. Thanks for changing!
