### ISSUE TITLE
PAC-12 Conference

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#387]
Colors:

PMS 662c >> 004B91
PMS 5395c >> 00274D
PMS 2935c >> 0076C0
Rich Black >> 000007 

Source: PAC 12 Style Guide from University of Utah's Marketing and Communications website -- 
http://umc.utah.edu/wp-content/uploads/sites/15/2014/12/Pac12_StyleGuide_UTAH.pdf, page 11.

**Comment by galengidman** [comment]
Published.
