### ISSUE TITLE
University of Washington

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#394]
Primary Colors:

Purple: 4b2e83
Gold: b7a57a (non-web); e8e3d3 (web)
Metallic Gold: 85754d

Source: https://www.washington.edu/brand/graphic-elements/primary-color-palette/

**Comment by dkhamsing** [comment]
Added purple `4b2e83`
Submitted brand `1322` for review, thanks

**Comment by galengidman** [comment]
Published.
