### ISSUE TITLE
CC (Creative Commons)

### ISSUE THREAD

**Issue by englishextra** [brandcolors/feedback#406]
Really Handy dark colors at the bottom of color list here:

 https://wiki.creativecommons.org/wiki/Colors

When it comes to making a CC license button in svg you start searching for their official colors

I would suggest one color closer to dark gray / silver which is largely recognizable. I guess it is 
# a7a9ac

Thanks.

**Comment by galengidman** [comment]
Published.

**Comment by englishextra** [comment]
@galengidman thanks
