### ISSUE TITLE
AT&T colors are incorrect

### ISSUE THREAD

**Issue by mrdehate** [brandcolors/feedback#409]
Hi, I stumbled upon the [AT&T Brand Guidelines](https://brandcenter.att.com/content/dam/brandcenter/learn/PDFs/ATT_BrandTraining_QRG_Color-150407.pdf) that lists their official color codes, and noticed there are some errors in what's listed here.

The correct values are:
# ef6f00
# fcb314
# 0574ac
# 44c8f5

**Comment by dkhamsing** [comment]
thanks, paging @galengidman

**Comment by galengidman** [comment]
Updated.
