### ISSUE TITLE
[Request] Create an Apple.com palette 

### ISSUE THREAD

**Issue by CalebSussman** [brandcolors/feedback#410]
Logo: #FFFFFF / #000000
Menu bar / Header Text: #333333
Picture Backgrounds: #FCFCFC
Highlighted Text / Links: #1888CD
Site Background: #F3F3F3
Normal Text: #666666

**Comment by galengidman** [comment]
This has been requested many times over. Apple's hard because they don't seem to have an official set of brand colors — just a bazillion different shades of gray. I'm always on the lookout for something official, but I haven't found it yet.
