### ISSUE TITLE
Sprout Social

### ISSUE THREAD

**Issue by arlodesign** [brandcolors/feedback#411]
sproutsocial.com
# 59cb59 :arrow_backward: Primary brand color
# f3f4f4
# 75DD66
# 2BB656
# 0CA750
#364141

Source: http://sproutsocial.com/brand-assets (And I'm on the design team :smile:)

**Comment by dkhamsing** [comment]
Submitted brand `1334` for review, thanks

**Comment by galengidman** [comment]
This was published 3/30/16... just forgot to update this. Published.
