### ISSUE TITLE
Medium

### ISSUE THREAD

**Issue by larsenwork** [brandcolors/feedback#413]
**Greens**
#00AB6C
#14C767
#0BE370
#32FC8D

**Grays**
#58595B
#808184
#A6A8AB
#D0D2D3

Picked from images here: https://github.com/Medium/medium-logos/tree/master/logo

**Comment by dkhamsing** [comment]
Submitted brand `1342` for review, thanks

**Comment by AlinaWithAFace** [comment]
They went in-depth on the site's design colors [here](https://medium.com/designing-medium/green-4-2-0-64959f9381a7#.qhugqssva)

![image](https://cloud.githubusercontent.com/assets/8976597/12869619/f385f3d2-ccf2-11e5-8d4c-0f254fad3b72.png)

**Comment by galengidman** [comment]
Updated.
