### ISSUE TITLE
Add Milligram

### ISSUE THREAD

**Issue by cjpatoilo** [brandcolors/feedback#417]
**Colors:**
`#9b4dca`
`#f4f5f6`
`#606c76`

**Links:**
http://milligram.io
http://github.com/milligram/milligram

**Comment by cjpatoilo** [comment]
Hey @galengidman Is this project still active?

**Comment by galengidman** [comment]
@cjpatoilo - Yes, I just have an embarrassing number of backlogged submissions. I've added Milligram. Thanks for you patiences.
