### ISSUE TITLE
Hewlett Packard Enterprise

### ISSUE THREAD

**Issue by pltrdy** [brandcolors/feedback#419]
Hi,

HPE isn't in your collection, 
See logo spec. here https://saas.hpe.com/pt-pt/content/terms 

Corresponding colors are:
Green Rectangle: #00B388
Gray Background: #425462 

Nice work tho, thx

**Comment by dkhamsing** [comment]
Submitted brand `1348` as HPE for review, thanks

**Comment by galengidman** [comment]
Published.
