### ISSUE TITLE
Asana Rebrand

### ISSUE THREAD

**Issue by AlinaWithAFace** [brandcolors/feedback#420]
They went through [pretty major design changes](https://blog.asana.com/2015/10/teamwork-is-beautiful-introducing-asanas-new-look/) a while back.
![image](https://cloud.githubusercontent.com/assets/8976597/12869695/76b04b80-ccf4-11e5-8978-3edf76fc5100.png)

**Comment by dkhamsing** [comment]
This brand update requires @galengidman

**Comment by galengidman** [comment]
Updated.
