### ISSUE TITLE
2016 Lyft Colors

### ISSUE THREAD

**Issue by RisingSkylar** [brandcolors/feedback#425]
It would appear that Lyft has once again updated their colorset. 

- Hot Pink - #FF00BF
- Mulberry - #352384
- Charcoal - 333447
- Bone - #F3F3F5

**Comment by dkhamsing** [comment]
Thx

Paging @galengidman

**Comment by galengidman** [comment]
@RisingSkylar where did you source these from?

**Comment by RisingSkylar** [comment]
@galengidman The [Lyft API Guidelines](http://bit.ly/1Wa12r1) that I stumbled upon in their [Developer Documentation](http://lft.to/1Wa1lC9).

**Comment by galengidman** [comment]
Perfect. Updated.
