### ISSUE TITLE
Official colors for Gitter

### ISSUE THREAD

**Issue by tommygebru** [brandcolors/feedback#430]
Really enjoy using your site !

So I spoke with the Gitter team, this is their official colorpath:

46BC99, F68D42, ED1965, F2F0ED, 3A3133
https://gitter.im/

**Comment by tommygebru** [comment]
![0ik5t8z](https://cloud.githubusercontent.com/assets/7606025/13296992/0149a252-dae5-11e5-86e1-b3988b1b55c0.png)

**Comment by dkhamsing** [comment]
Submitted brand `1355` for review, thanks

**Comment by tommygebru** [comment]
you bet !

**Comment by galengidman** [comment]
Published.

**Comment by tommygebru** [comment]
very cool ! thanks a bunch
