### ISSUE TITLE
Viber

### ISSUE THREAD

**Issue by podabed** [brandcolors/feedback#432]
Thanks for contributing to http://brandcolors.net/

Please fill this out below (colors should be comma-separated hex-codes, i.e. 0063dc,ff0084)

- *Brand Name*: Viber
- *Brand Colors*: color-hex.com/color-palette/4740
- *Brand URL*: viber.com
- *New Brand*: no
- *Where/how you found the brand colors*: color-hex.com/color-palette/4740

**Comment by dkhamsing** [comment]
Submitted brand `1358` for review, thanks

**Comment by galengidman** [comment]
Added.
