### ISSUE TITLE
Ferrari

### ISSUE THREAD

**Issue by AshrafAbuBakr** [brandcolors/feedback#436]
- *Brand Name*:Ferrari
- *Brand Colors*: 229B4E, FFFFFF, EE1D24, FFF302, 000000
- *Brand URL*: www.ferrari.com
- *New Brand*: no
- *Where/how you found the brand colors*: Extracted from their logo.

**Comment by dkhamsing** [comment]
Submitted the main color EE1D24 for now as brand `1360` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
