### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by AshrafAbuBakr** [brandcolors/feedback#437]
- *Brand Name*:LinkedIn
- *Brand Colors*:0077B5, 313335, 86888A, CACCCE, 00A0DC, 8D6CAB, DD5413, E68523
- *Brand URL*:www.linedin.com
- *New Brand*: no
- *Where/how you found the brand colors*:Their color guidelines.

**Comment by dkhamsing** [comment]
@AshrafAbuBakr linkedin is already on http://brandcolors.net/ 
I guess the black color is not the same @galengidman if you want to update

**Comment by AshrafAbuBakr** [comment]
Oh sorry, I hadn't noticed.
I don't want to update I think the current colors are right.
