### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by sebastien-bartoli** [brandcolors/feedback#438]
Hello guys, thank you for your great work ! Really useful :)

- *Brand Name*: Gitlab
- *Brand Colors*: FCA326, FC6D26, E24329, 554488
- *Brand URL*: https://about.gitlab.com
- *New Brand*: yes
- *Where/how you found the brand colors*: https://gitlab.com/gitlab-com/gitlab-artwork/blob/master/colors and from their CSS for the purple

**Comment by dkhamsing** [comment]
Submitted brand `1364` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
