### ISSUE TITLE
Periscope

### ISSUE THREAD

**Issue by konstantinbrazhnik** [brandcolors/feedback#439]
- *Brand Name*: Periscope
- *Brand Colors*: 40a4c4,d75444
- *Brand URL*:http://periscope.tv
- *New Brand*: yes
- *Where/how you found the brand colors*: https://www.periscope.tv/press

**Comment by dkhamsing** [comment]
Submitted brand `1366` for review, thanks

**Comment by galengidman** [comment]
Published, thanks!
