### ISSUE TITLE
Avira AntiVir

### ISSUE THREAD

**Issue by MarioBasa2002** [brandcolors/feedback#440]
- _Brand Name_: Avira Antivirus
- _Brand Colors_: D40000,FFFFFF
- _Brand URL_: https://www.avira.com/de/
- _New Brand_: yes
- _Where/how you found the brand colors_: https://de.wikipedia.org/wiki/Avira_Antivirus

**Comment by dkhamsing** [comment]
Submitted brand `1371` for review, thanks

**Comment by dkhamsing** [comment]
@MarioBasa2002 any reason this was closed?

**Comment by dkhamsing** [comment]
Please leave this open, will be closed if added to the site
Thanks

**Comment by galengidman** [comment]
This was published April 5, 2016 and I just forgot to close the issue.
