### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Boltgolt** [brandcolors/feedback#441]
- *Brand Name*: Discord
- *Brand Colors*: 7289DA,FFFFFF,99AAB5,2C2F33,23272A
- *Brand URL*: [discordapp.com](https://discordapp.com)
- *New Brand*: yes
- *Where/how you found the brand colors*: [discordapp.com/branding](https://discordapp.com/branding)

**Comment by dkhamsing** [comment]
Submitted brand `1370` for review, thanks

**Comment by galengidman** [comment]
Published.
