### ISSUE TITLE
Categories/Tags

### ISSUE THREAD

**Issue by dkhamsing** [brandcolors/feedback#443]
Maybe it makes sense to have add categories or tags for each brand, i.e. airline, university, etc..

**Comment by galengidman** [comment]
I have thought about that, but the work involved in initial tagging and then maintaining the tags would be massive. It's something I know I don't want to do and I don't want to ask of other people either. Which leads me to think about letting users do it as they browse the site, but then you have to worry about validation. That's also a lot more work from a development prospective too.

Thoughts?

**Comment by dkhamsing** [comment]
Crowdsourcing this would be ideal. Could this be exposed on GitHub and then approval is done through pull request? Is that more work, less ?

**Comment by galengidman** [comment]
You're saying expose the site source in GH? All the data is stored in a database, so I don't think that solves any of our issues.

**Comment by dkhamsing** [comment]
Ah I see

I guess anything would involve some dev work

**Comment by dkhamsing** [comment]
Maybe best to add tagging on site by any user.. up to you if you want to approve all changes but that would fill the cap fastest

Maybe one compromise is that tag creation is controlled
