### ISSUE TITLE
Update Evernote colors

### ISSUE THREAD

**Issue by augbog** [brandcolors/feedback#444]
*Brand Name*: Evernote
*Brand Colors*: #2DBE60, #7B868A
*Brand URL*: https://evernote.com/
*New Brand*: no
*Where/how you found the brand colors*: https://evernote.com/brand/color-palette/

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.

**Comment by augbog** [comment]
Thanks :)
