### ISSUE TITLE
University of Wisconsin-Milwaukee

### ISSUE THREAD

**Issue by cjmaio** [brandcolors/feedback#445]
- _Brand Name_: University of Wisconsin-Milwaukee
- _Brand Colors_: #ffbd00, #000000, #98c646, #694d88, #5382af, #d06d34, #5f9a38, #474d52
- _Brand URL_: http://uwm.edu/branding/uwms-brand/uwm-colors/
- _New Brand_: no
- _Where/how you found the brand colors_: Web developer here.

**Comment by galengidman** [comment]
Published.
