### ISSUE TITLE
Pen and Lens Brand colors

### ISSUE THREAD

**Issue by PLDevelopement** [brandcolors/feedback#446]
- _Brand Name_: Pen and Lens
- _Brand Colors_:
  Main Brand: 
  ad9682,
  Subodinate: 
  f8cbc9,
  ffe75a,
  a5d069,
  5b8abb
- _Brand URL_: www.penandlensdesign.com
- _New Brand_: yes
- _Where/how you found the brand colors_: I'm the Founder/Designer/Owner
  We've got multiple brands, but I've listed here only the main colors for each brand, so you don't have to submit 6 brands and 30 colors!

Best,

**Comment by galengidman** [comment]
Thanks for submitting, but I have a policy about not adding colors for design agencies, so I'll have to pass on this.
