### ISSUE TITLE
RE/MAX

### ISSUE THREAD

**Issue by ncrause** [brandcolors/feedback#447]
- _Brand Name_: RE/MAX
- _Brand Colors_: CE0000, 0054A0
- _Brand URL_: http://www.remax.com, brand spec: https://remaxintegra.zendesk.com/hc/en-us/articles/204908515-Official-RE-MAX-Colors
- _New Brand_: no
- _Where/how you found the brand colors_: I work with realtors on websites and print materials

**Comment by dkhamsing** [comment]
Submitted brand `1375` for review, thanks

**Comment by galengidman** [comment]
Published.
