### ISSUE TITLE
University of Illinois at Urbana-Champaign

### ISSUE THREAD

**Issue by wyaeiga** [brandcolors/feedback#448]
- _Brand Name_: University of Illinois at Urbana-Champaign
- _Brand Colors_: #002058, #E87722
- _Brand URL_: http://illinois.edu/
- _Where/how you found the brand colors_: http://identitystandards.illinois.edu/graphicstandardsmanual/generalguidelines/colors.html

**Comment by galengidman** [comment]
Published.
