### ISSUE TITLE
Deezer - Musik

### ISSUE THREAD

**Issue by MarioBasa2002** [brandcolors/feedback#450]
- _Brand Name_: Deezer
- _Brand Colors_: f6836c,ed1c24,fff200,f680c5,ec008c,d9ed84,b2db18,b2e6fa,59caf5,231f20
- _Brand URL_: https://www.deezer.com/
- _New Brand_: yes
- _Where/how you found the brand colors_: https://de.wikipedia.org/wiki/Deezer
- _Software_: paint.net (_http://www.getpaint.net/_)

**Comment by galengidman** [comment]
Published.
