### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by BaburMB** [brandcolors/feedback#451]
- [x] _Brand Name_: Google Chrome
- [x] _Brand Colors_: 4586f3, 4586f3, 4586f3, dc493a
- [x] _Brand URL_: https://www.google.com/chrome/
- [x] _Where/how you found the brand colors_: Adobe Photoshop Color Picker
- [x] New on brandcolors.net

**Comment by dkhamsing** [comment]
@BaburMB the first 3 colors are the same, can you update?

**Comment by BaburMB** [comment]
done

**Comment by dkhamsing** [comment]
Submitted brand `1376` for review, thanks

**Comment by galengidman** [comment]
Choosing not to publish since this is basically a dupe of Google proper. Thanks for taking the time to submit though.
