### ISSUE TITLE
Snapchat

### ISSUE THREAD

**Issue by danphilibin** [brandcolors/feedback#452]
- [x] _Brand Name_: Snapchat
- [x] _Brand Colors_: fffc00
- [x] _Brand URL_: https://snapchat.com
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: snapchat.com

**Comment by dkhamsing** [comment]
Submitted brand `1379` for review, thanks

**Comment by galengidman** [comment]
Looks like this has been published for a while. Closing.
