### ISSUE TITLE
University of Hamburg

### ISSUE THREAD

**Issue by modprobe** [brandcolors/feedback#453]
- [x] _Brand Name_: Universität Hamburg
- [x] _Brand Colors_: e2001a,009cd1,3b515b
- [x] _Brand URL_: www.uni-hamburg.de
- [ ] _Updating brand_
- [x] _Where/how you found the brand colors_: [Uni Hamburg CD Manual](https://www.uni-hamburg.de/beschaeftigtenportal/services/oeffentlichkeitsarbeit/corporate-design/manual/corporate-manual-2016.pdf)

**Comment by dkhamsing** [comment]
Submitted brand `1382` for review, thanks

**Comment by galengidman** [comment]
Published.
