### ISSUE TITLE
ÖBB

### ISSUE THREAD

**Issue by modprobe** [brandcolors/feedback#454]
- [x] _Brand Name_: ÖBB (Österreichische Bundesbahnen/Austrian Federal Railways)
- [x] _Brand Colors_: e2002a,6e6e6e
- [x] _Brand URL_: www.oebb.at
- [ ] _Updating brand_
- [x] _Where/how you found the brand colors_: [ÖBB CD Manual](http://www.heiderklausner.at/fileadmin/user_upload/clients/OEBB/OeBB-CD-Manual-Auszug__c_heiderklausner.pdf), made available by developing agency

**Comment by galengidman** [comment]
Published.
