### ISSUE TITLE
Twitter Brand Color

### ISSUE THREAD

**Issue by zachgibson** [brandcolors/feedback#456]
- *Brand Name*: Twitter
- *Brand Colors*: #1da1f2
- *Brand URL*: twitter.com
- *Updating brand* x
- *Where/how you found the brand colors*: https://twitter.com/ inspect logo icon color and various other UI to see the blue brand color has changed.

**Comment by galengidman** [comment]
Hey Zach.

I appreciate the submission, but I'm going to keep it as is until I see this page change: https://about.twitter.com/company/brand-assets

If you happen to see an update on that though, by all means let me know and I'll get it updated.

Thanks!
— Galen
