### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by ifvictr** [brandcolors/feedback#457]
- [x] *Brand Name*: Apple
- [x] *Brand Colors*: ffffff, 999999, 000000
- [x] *Brand URL*: https://apple.com
- [ ] *Updating brand*
- [x] *Where/how you found the brand colors*: http://designpieces.com/palette/apple-colour-palette-hex-and-rgb/

**Comment by dkhamsing** [comment]
Paging @galengidman

**Comment by galengidman** [comment]
I've seen a lot of different takes on Apple's brand colors, but I'm not convinced any of them are very official. I've reached out to a designer friend of mine that works there for official colors — we'll see what he says.
