### ISSUE TITLE
Messenger

### ISSUE THREAD

**Issue by osternaudClem** [brandcolors/feedback#458]
- [x] _Brand Name_: Messenger
- [x] _Brand Colors_: 0084ff
- [x] _Brand URL_: https://www.messenger.com
- [x] _Where/how you found the brand colors_: https://developers.facebook.com/docs/messenger/brand-guidelines (link to PSD)

**Comment by dkhamsing** [comment]
Submitted brand `1381` for review, thanks

**Comment by galengidman** [comment]
Published.
