### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by alex100001** [brandcolors/feedback#459]
- [X] *Brand Name*: Instagram
- [X] *Brand Colors*: e4405f, 000000, ffffff
- [X] *Brand URL*: https://www.instagram-brand.com/
- [X] *Updating brand* 
- [X] *Where/how you found the brand colors*: Instagram's brand website features this pink colour as a fallback for the header background in the page's CSS, and uses it for various other assets on the page, suggesting this is the main colour that they've picked from the new gradient background.

**Comment by dkhamsing** [comment]
This update requires @galengidman

**Comment by galengidman** [comment]
There's a screenshot of the official palette at 0:29 secs in this video: https://vimeo.com/166138104 I've updated with that.

(ht: @garand)
