### ISSUE TITLE
University of Waterloo

### ISSUE THREAD

**Issue by assefamaru** [brandcolors/feedback#460]
- [x] _Brand Name_: University of Waterloo
- [x] _Brand Colors_: 
  - Official palette  ~> 000000, FFFFFF, FCD450
  - Neutral palette ~> EEEEEE, 757575
  - Faculty palette ~> 009AA6, 007F8A, E98300, AC6100, CCAAFF, 57068C, B6BF00, 747800, FF88DD, E0249A, 77BBFF, 0073CF, F77777, 96172E
- [x] _Brand URL_: [https://uwaterloo.ca/](https://uwaterloo.ca/)
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: [https://uwaterloo.ca/brand-guidelines-and-tools/visual-identity/digital-colour-palette](https://uwaterloo.ca/brand-guidelines-and-tools/visual-identity/digital-colour-palette)

**Comment by dkhamsing** [comment]
Submitted brand `1419` for review, thanks

**Comment by galengidman** [comment]
Published.
