### ISSUE TITLE
Fiskars Brands Inc.

### ISSUE THREAD

**Issue by trevorberman** [brandcolors/feedback#461]
- [x] _Brand Name_: Fiskars Brands Inc.
- [x] _Brand Colors_: ff8e00,ffffff,000000,955214,55601c,005172
- [x] _Brand URL_: http://www2.fiskars.com/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: I work on the Fiskars Americas Marcomm team. Colors taken from the brand style guide, current 5/18/16. (See attached screen-captures.)
  ![screen shot 2016-05-18 at 3 55 30 pm](https://cloud.githubusercontent.com/assets/8570863/15374992/9a36da60-1d12-11e6-96a2-044f8eb22c1c.png)
  ![screen shot 2016-05-18 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/8570863/15375010/a2e37b28-1d12-11e6-8058-93d4ad2650c5.png)

**Comment by dkhamsing** [comment]
Submitted brand `1384` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.

**Comment by nadiTime** [comment]
Trevor, where can I find the complete Fiskars style guide?

**Comment by trevorberman** [comment]
@nadiTime The style guide for Fiskars Americas is an internal corporate document. We don't have it published for public view. Is there something specific you were looking for in it, or some reason you want the complete version?

**Comment by nadiTime** [comment]
@trevorberman ,
Im an Industrial design student at HIT Israel. Did a DNA project about FISKARS and was looking for information for my research. 
The final goal was to design a Vacuum cleaner for the company 
Attached is my final model
![2-01](https://user-images.githubusercontent.com/10961775/44628519-b9389500-a949-11e8-9364-fc1278ec2ed0.jpg)

**Comment by trevorberman** [comment]
@nadiTime Thanks for sharing! I've passed this along to the brand manager for Fiskars Americas to see if she can get you further internal exposure. Thinking maybe product managers and/or engineers might be interested to see your initiative. Will pass back any feedback. In the meantime, you might also try reaching out to our European offices in Finland. https://www.fiskars.eu/ They have a slightly different product lineup and also a whole stable of product managers/engineers of their own. Possibly another avenue for a foot in the door. 😉
