### ISSUE TITLE
Codepen

### ISSUE THREAD

**Issue by MrFevs** [brandcolors/feedback#462]
![black-large](https://cloud.githubusercontent.com/assets/12731372/15424037/54f7f7ba-1e78-11e6-8da1-172ac6f6c8b6.png)

- [x] _Codepen_:
- [x] _000, fff, 0ebeff, 47cf73, ae63e4, fcd000_:
- [x] _codepen.io_:
- [ ] _Updating brand_ 
- [x] _Looking at their logo and inspected elements of their website for consistent colours_:

**Comment by dkhamsing** [comment]
Submitted brand `1418` for review, thanks

**Comment by galengidman** [comment]
Not sure these feel right. I've contacted Chris Coyier for an official list. Stand by.

**Comment by galengidman** [comment]
Found this: http://codepen.io/guide/

Published.
