### ISSUE TITLE
Ask.fm Brand colors

### ISSUE THREAD

**Issue by brennced** [brandcolors/feedback#463]
- [x] _Brand Name_: Ask.fm 
- [x] _Brand Colors_: FF643C,24A3AE,434A50,2F7F47,DB3552,2D5592,9452AA,E55EA2,BB8BB8
- [x] _Brand URL_: http://ask.fm/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Account settings

**Comment by galengidman** [comment]
Published.
