### ISSUE TITLE
Brand Request: Wikipedia

### ISSUE THREAD

**Issue by tommygebru** [brandcolors/feedback#467]
Just inspecting I got these colors for **Wikipedia:**
- [x] _Brand Name_:**Wikipedia**
- [x] _Brand Colors_: #e8f1ff, #6b6b6b, #7eb6e4, #165c91

**Comment by dkhamsing** [comment]
Submitted brand `1417` for review, thanks

**Comment by galengidman** [comment]
As per https://wikimediafoundation.org/wiki/Visual_identity_guidelines#toc-colorvalues I believe that their official color scheme is simply a grayscale. I've published the values on the site. Thanks for sending this in.

**Comment by tommygebru** [comment]
Thanks for sharing this, I had made a simple app with what I assumed were there brandcolors

https://tommygebru.github.io/wiki/

**Comment by galengidman** [comment]
No problem. I like the colors on your app — if it were me, I'd keep 'em.
