### ISSUE TITLE
Brand Request: University of Florida

### ISSUE THREAD

**Issue by bigbadtrumpet** [brandcolors/feedback#468]
- [X] _Brand Name_: University of Florida
- [X] _Brand Colors_: #FA4616, #0021A5
- [X] _Brand URL_: http://www.ufl.edu/
- [ ] _Updating brand_ No
- [X] _Where/how you found the brand colors_: [http://identity.ufl.edu/color/](http://identity.ufl.edu/color/) under the "Primary Color Palette" section

**Comment by galengidman** [comment]
Published.
