### ISSUE TITLE
Brand color: Debian

### ISSUE THREAD

**Issue by brennced** [brandcolors/feedback#469]
- [x] _Brand Name_: Debian
- [x] _Brand Colors_: #C70036
- [x] _Brand URL_: https://www.debian.org/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Picked in logo

**Comment by dkhamsing** [comment]
Submitted brand `1389` for review, thanks

**Comment by galengidman** [comment]
Published.
