### ISSUE TITLE
Brand Request: San Francisco 49ers

### ISSUE THREAD

**Issue by JackReis** [brandcolors/feedback#470]
- [x] *Brand Name*: San Francisco 49ers
- [x] *Brand Colors*: e91e22,c8aa76,000000
- [x] *Brand URL*: [http://www.49ers.com/](http://www.49ers.com/)
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: I'm a designer at Kahuna (startup in Redwood City, CA) - and a 49ers fan. I am also big on color...  so I grabbed the logo and sampled the color using ColorZilla, then verified with the values I got when I opened the logo file (from http://www.49ers.com/) in Photoshop. This is the logo file I used: [http://prod.static.49ers.clubs.nfl.com/assets/img/bg/logo.png](http://prod.static.49ers.clubs.nfl.com/assets/img/bg/logo.png). There are two colors used in the text on the website, but I opted for the actual logo colors instead. The full library of all 5 colors plus the logo in a PSD is available at [http://adobe.ly/22MRWSv](http://adobe.ly/22MRWSv). Let me know if you have any questions! I'm @jackreis on Twitter, would love to exchange follows as this is a cool project and you seem a valuable member of the online design community. Thanks for your work on brandcolors.net!

**Comment by dkhamsing** [comment]
Submitted brand `1391` for review, thanks

**Comment by galengidman** [comment]
Published.
