### ISSUE TITLE
Brand Request: San Francisco Giants

### ISSUE THREAD

**Issue by JackReis** [brandcolors/feedback#471]
- [x] *Brand Name*: San Francisco Giants
- [x] *Brand Colors*: fd5a1e,000000
- [] *Brand URL*: [sfgiants.com](http://sanfrancisco.giants.mlb.com/index.jsp?c_id=sf)
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: I'm a designer at Kahuna (startup in Redwood City, CA) - and a Giants fan. I am also big on color...  So I grabbed the SVG logo at [http://sanfrancisco.giants.mlb.com/documents/6/0/2/111217602/SF_header_logo_mpqkye7c.svg](http://sanfrancisco.giants.mlb.com/documents/6/0/2/111217602/SF_header_logo_mpqkye7c.svg) after inspecting the element on the official MLB Giants page. That orange is also used on their official website, which confirms it is legit (#FD5A1E) - it usually appears on a pure black background on their merchandise, and the website has a pure black background too, so I added #000000 to make it complete. Simple but recognizable! I'm headed to the game vs. the Red Sox tonight. Let me know if you have any questions! I'm @jackreis on Twitter, would love to exchange follows as this is a cool project and you seem a valuable member of the online design community. Thanks for your work on brandcolors.net!

**Comment by galengidman** [comment]
Published.
