### ISSUE TITLE
Google Plus color seems to be inaccurate

### ISSUE THREAD

**Issue by codener** [brandcolors/feedback#472]
Dear maintainer,
Thanks for the super-helpful brand colors platform. I use it every now and then.

However, when I took the Google+ color today, I found it different from what is stated by Google itself. According to https://developers.google.com/+/branding-guidelines#google-icon-branding-guidelines it should be #dd4b39.

Maybe it should be updated?
Cheers

**Comment by dkhamsing** [comment]
pagin @galengidman

**Comment by galengidman** [comment]
Fixed. Thanks!
