### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by balcsida** [brandcolors/feedback#474]
- [x] _Brand Name_: Windows
- [x] _Brand Colors_:  #0078d7,#002050,#ffb900,#d83b01,#e81123,#b4009e,#5c2d91,#008272,#107c10
- [x] _Brand URL_: https://windows.com
- [x] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Windows10_guidelines.pdf - Windows Brand Guidelines - April 2015 - Microsoft Confidential

**Comment by balcsida** [comment]
![windows10_guidelines-26](https://cloud.githubusercontent.com/assets/1768446/17877632/fbfd8a64-68e4-11e6-86b8-59c739b9a4c4.png)

**Comment by galengidman** [comment]
Published.
