### ISSUE TITLE
Microsoft Surface

### ISSUE THREAD

**Issue by balcsida** [brandcolors/feedback#475]
- [x] _Brand Name_: Microsoft Surface
- [x] _Brand Colors_: #0078d7,#ffffff,#eeeeee,#737373,#505050,#000000
- [x] _Brand URL_: https://www.microsoft.com/surface/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Microsoft_Surface_brand_guidelines.pdf

**Comment by galengidman** [comment]
Published.
