### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by heyjoecampbell** [brandcolors/feedback#476]
Provide the ability to search by color (i.e. purple)
This would require associating a color name to each hex color.

Here's a mock-up of how the search box could convey the additional feature:
http://imgur.com/qSDsoF1

**Comment by galengidman** [comment]
_Theoretically_, this would be awesome. _Realistically_, it'd be a huge undertaking.

Currently the site has 1333 unique colors that would need to be tagged, which would require a lot of man hours and a change in the back-end data structure. That is, unless this could somehow be automated — personally I don't know how you would do that, although perhaps it's possible.

I'll keep this in the back of my mind for future versions, but I don't see this as a top priority at the moment. Thanks for taking the time to chime in though.
