### ISSUE TITLE
Brand request: Kiva

### ISSUE THREAD

**Issue by awallin** [brandcolors/feedback#477]
- [ ] *Brand Name*: Kiva
- [ ] *Brand Colors*: #63a541, #236133, #26b6e8
- [ ] *Brand URL*: Kiva.org
- [ ] *Where/how you found the brand colors*: I'm the design director at Kiva. We have recently redesign/rebranded our website. You can find our full brand guide with all colors here: https://brandfolder.com/kiva/brand-guidelines

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by dkhamsing** [comment]
Nevermind this is a new brand

**Comment by awallin** [comment]
Any chance we these Kiva colors can be added?

**Comment by galengidman** [comment]
Published. Thanks for sending that in.
