### ISSUE TITLE
Brand Request: Steam

### ISSUE THREAD

**Issue by paoloposo** [brandcolors/feedback#480]
- [ ] *Brand Name*: Steam
- [ ] *Brand Colors*: 000000
- [ ] *Brand URL*: https://steampowered.com/
- [ ] *Updating brand* 
- [ ] *Where/how you found the brand colors*: https://partner.steamgames.com/documentation/branding

**Comment by paoloposo** [comment]
What exactly does "applicable" mean in this context? That the brand has this feature?

**Comment by dkhamsing** [comment]
uh we'll have to ask @galengidman

**Comment by galengidman** [comment]
Not sure I understand your question @paoloposo. Are you referring to the issue template? I think that's in reference to updating an existing brand.

I've published the brand.

**Comment by dkhamsing** [comment]
ah right
ok

**Comment by paoloposo** [comment]
@galengidman Yes, I was reffering to the issue template. I was wondering whether I should tick the boxes when requesting a new brand.

**Comment by dkhamsing** [comment]
@paoloposo the idea is to leave that particular checkbox empty if it's a new brand
