### ISSUE TITLE
Brand Request: Bartolini BRT

### ISSUE THREAD

**Issue by 3DDario** [brandcolors/feedback#481]
- [x] _Brand Name_: Bartolini - BRT
- [x] _Brand Colors_: C90F24
- [x] _Brand URL_: http://www.brt.it/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Website, logo

"Bartolini" is the old (and best known) name. The actual (and official) name is "BRT"

**Comment by galengidman** [comment]
Published.
