### ISSUE TITLE
Twitter color seems to be wrong

### ISSUE THREAD

**Issue by codener** [brandcolors/feedback#482]
The Twitter color of brandcolors.com does not match the [official guidelines](https://brand.twitter.com/de.html).

- [x] *Brand Name*: Twitter
- [x] *Brand Colors*: #1DA1F2
- [x] *Brand URL*: twitter.com
- [x] *Updating brand*: yes
- [x] *Where/how you found the brand colors*: https://brand.twitter.com/de.html, either read the guideline document or take the download button's color

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated, thank you.
