### ISSUE TITLE
Brand request: Yii Framework

### ISSUE THREAD

**Issue by alexantr** [brandcolors/feedback#483]
- [x] _Brand Name_: Yii Framework
- [x] _Brand Colors_: d8582b,16a314,3b6fba
- [x] _Brand URL_: http://www.yiiframework.com/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Slogan from homepage: "The Fast, Secure and Professional PHP Framework"

**Comment by galengidman** [comment]
Published.
