### ISSUE TITLE
Brand Request: Studio Arrival

### ISSUE THREAD

**Issue by jabedbd** [brandcolors/feedback#484]
- [ ] *Brand Name*: Studio Arrival
- [ ] *Brand Colors*: e24327, fff
- [ ] *Brand URL*: http://studioarrival.com/
- [ ] *Updating brand* 
- [ ] *Where/how you found the brand colors*: From their logo, website and their fb page.

**Comment by galengidman** [comment]
Sorry, but it is our policy not to add brand colors of design agencies. Thanks for taking the time to submit though.
