### ISSUE TITLE
Brand request: Issuu

### ISSUE THREAD

**Issue by njy** [brandcolors/feedback#485]
- [x] _Brand Name_: Issuu
- [x] _Brand Colors_: f36d5d
- [x] _Brand URL_: https://issuu.com/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: at https://issuu.com/press , in the "Logo guidelines" section, I've picked the logo color using Chrom Dev Tools' color picker + confirmed it was it by looking at the hex color directly in their site's css

**Comment by galengidman** [comment]
Published.
