### ISSUE TITLE
Wrong Color for Medium

### ISSUE THREAD

**Issue by willium** [brandcolors/feedback#486]
Nitpicky, however, the color you have for medium is wrong:

You list it as `#00AB6B` when it is infact `#00AB6C`
- [x] _Brand Name_: Medium
- [x] _Brand Colors_: `#00AB6C`
- [x] _Brand URL_: https://medium.com
- [x] _Updating brand_ True
- [x] _Where/how you found the brand colors_: https://medium.com/policy/logos-and-brand-guidelines-f1a01a733592#.sb94i7tv2

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
