### ISSUE TITLE
Brand request: Estimote

### ISSUE THREAD

**Issue by TheRealGitCub** [brandcolors/feedback#487]
- [x] _Brand Name_: Estimote
- [x] _Brand Colors_: 6F1A57,373B96,E88AB4,60B5D9,CCC92A,759B86
- [x] _Brand URL_: http://estimote.com/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Official Android Application's Icon ([image](https://lh6.ggpht.com/f0Gxje81WM8Pn18xs5xB0VK1FMwNtNgoFnyKSgbqxfo-lKTRDl1vnXHHca7p2rM2BsA=w300) | [app](https://play.google.com/store/apps/details?id=com.estimote.apps.main))

**Comment by galengidman** [comment]
Published.
