### ISSUE TITLE
Brand Request: Georgia Southern University

### ISSUE THREAD

**Issue by TheRealGitCub** [brandcolors/feedback#488]
- [x] _Brand Name_: Georgia Southern University
- [x] _Brand Colors_: 041E42,A99260
- [x] _Brand URL_: http://georgiasouthern.edu
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: [Identity Standards Guide, Page 2](http://news.georgiasouthern.edu/marketing/wp-content/uploads/sites/4/GS_IdentityStdsQuickGuide_Mar2016.pdf), I am also a web developer for the University

**Comment by galengidman** [comment]
Published.
