### ISSUE TITLE
Brand Request: JBL

### ISSUE THREAD

**Issue by TheRealGitCub** [brandcolors/feedback#489]
- [x] _Brand Name_: JBL
- [x] _Brand Colors_: ff6600
- [x] _Brand URL_: http://www.jbl.com/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: Went to the website and found the Hex code in the CSS. The default search box background is #f60, seeming to match the logo itself.

**Comment by dkhamsing** [comment]
Submitted brand `1402` for review, thanks

**Comment by galengidman** [comment]
Published.
