### ISSUE TITLE
Brand Request: SunTrust

### ISSUE THREAD

**Issue by TheRealGitCub** [brandcolors/feedback#491]
- [x] _Brand Name_: SunTrust
- [x] _Brand Colors_: f58025,f8a131,114A82
- [x] _Brand URL_: http://suntrust.com
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: CSS of the company's [Investor Relations site](http://investors.suntrust.com/overview/default.aspx)

**Comment by dkhamsing** [comment]
Submitted brand `1416` for review, thanks

**Comment by galengidman** [comment]
Published.
