### ISSUE TITLE
Brand Request: Google Allo

### ISSUE THREAD

**Issue by brainscript** [brandcolors/feedback#496]
- [x] _Brand Name_: Google Allo
- [x] _Brand Colors_: F5BB17
- [x] _Brand URL_: https://allo.google.com
- [ ] _Updating brand_ 
- [ ] _Where/how you found the brand colors_:

I picked the color from the logo icon on the website.
![Logo](https://allo.google.com/images/allo-logo.png)
(There are currently no brand guidelines ...)

**Comment by galengidman** [comment]
Published.
