### ISSUE TITLE
Brand Request: Google Duo

### ISSUE THREAD

**Issue by kutec** [brandcolors/feedback#497]
- [ ] _Brand Name_: Google Duo
- [ ] _Brand Colors_: #4285f4 (primary), #3d79e6 (secondary)
- [ ] _Brand URL_: https://duo.google.com/
- [ ] _Updating brand_ 
- [ ] _Where/how you found the brand colors_: I picked the color from the logo icon on the website.
  <img src="https://duo.google.com/images/duo-logo/Duo_gray.svg" alt="Logo" data-canonical-src="https://duo.google.com/images/duo-logo/Duo_gray.svg" style="max-width:100%;">

**Comment by galengidman** [comment]
Published.
