### ISSUE TITLE
GitHub - Missing purple

### ISSUE THREAD

**Issue by u01jmg3** [brandcolors/feedback#498]
- [x] *Brand Name*: GitHub
- [x] *Brand Colors*: #6e5494 (Purple)
- [x] *Brand URL*: https://gist.github.com/christopheranderton/4c88326ab6a5604acc29#file-github-brand-colors-aug-2015-css-L21-L23
- [x] *Updating brand*: Yes, purple is missing - can be seen on GitHub Desktop icon and [GitHub Enterprise](https://enterprise.github.com/home)
- [x] *Where/how you found the brand colors*: https://gist.github.com/christopheranderton/4c88326ab6a5604acc29#file-github-brand-colors-aug-2015-css-L21-L23

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
