### ISSUE TITLE
Brand Request: University of Michigan

### ISSUE THREAD

**Issue by teded32** [brandcolors/feedback#502]
- [x] _Brand Name_: University of Michigan
- [x] _Brand Colors_: 00274c,ffcb05
- [x] _Brand URL_: http://umich.edu/
- [ ] _Updating brand_ 
- [x] _Where/how you found the brand colors_: https://vpcomm.umich.edu/brand/style-guide/design-principles/colors

**Comment by dkhamsing** [comment]
Submitted brand `1415` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
