### ISSUE TITLE
Wrong Color for WhatsApp

### ISSUE THREAD

**Issue by svenfinger** [brandcolors/feedback#503]
The given green tone (#43d854) is slightly different to the one shown on their [Brand Resources](https://www.whatsappbrand.com/) website (#25D366). Maybe the other primary colors should also be added: e.g. #075E54,#25D366,#34B7F1

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated, thanks for sending that over.
