### ISSUE TITLE
Brand Request: Hitit Computer Services

### ISSUE THREAD

**Issue by yunuspekmezci** [brandcolors/feedback#505]
- [x] *Brand Name*: Hitit Computer Sevices
- [x] *Brand Colors*: a9363d 
- [x] *Brand URL*: http://hititcs.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Picked in logo

**Comment by galengidman** [comment]
From what I can tell, this seems to be a fairly localized brand, so I'm passing for now. Thanks for taking the time to submit.
