### ISSUE TITLE
Brand Request: Yedi

### ISSUE THREAD

**Issue by yunuspekmezci** [brandcolors/feedback#507]
- [x] *Brand Name*: Yedi
- [x] *Brand Colors*: 231f20
- [x] *Brand URL*: http://yedialacati.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Picked from website

**Comment by galengidman** [comment]
This doesn't seem to be a major brand judging off the website and it not showing up on the first page of a Google search for "yedi." Thanks for taking the time to submit, but I'll be passing on this one.
