### ISSUE TITLE
Brand Request: Dwolla

### ISSUE THREAD

**Issue by jbrewlet** [brandcolors/feedback#508]
- [X] *Brand Name*: Dwolla
- [X] *Brand Colors*: FF7404
- [X] *Brand URL*: https://dwolla.com
- [ ] *Updating brand* 
- [ ] *Where/how you found the brand colors*:

**Comment by dkhamsing** [comment]
Submitted brand `1421` for review, thanks

**Comment by galengidman** [comment]
Published.
