### ISSUE TITLE
Brand Request: LEGO

### ISSUE THREAD

**Issue by dc74089** [brandcolors/feedback#509]
- [x] *Brand Name*: LEGO
- [x] *Brand Colors*: f4070b,faed00,000000,ffffff
- [x] *Brand URL*: https://www.lego.com
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Picked from Logo

**Comment by dkhamsing** [comment]
Submitted brand `1422` for review, thanks

**Comment by galengidman** [comment]
Published, thanks!

**Comment by PeterShaggyNoble** [comment]
From the logo found [here](https://www.lego.com/en-us/aboutus/medialibrarydetails/logo), I extracted the red as #d11013.

**Comment by galengidman** [comment]
Looks like you're right. Updated
