### ISSUE TITLE
Brand Request: Vue

### ISSUE THREAD

**Issue by theus** [brandcolors/feedback#512]
- [x] *Brand Name*: Vue
- [x] *Brand Colors*: 41B883,35495E
- [x] *Brand URL*: https://vuejs.org/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Vue site

**Comment by dkhamsing** [comment]
Submitted brand `1423` for review, thanks

**Comment by galengidman** [comment]
Published, thanks.
