### ISSUE TITLE
Include a 1 px solid black border for (white-ish) colors 

### ISSUE THREAD

**Issue by tommygebru** [brandcolors/feedback#513]
Include a 1 px solid black border for (white-ish) colors that blend into the parent background... I am sure that I am not the only one who has trouble seeing some colors like #fafafa
thanks

**Comment by galengidman** [comment]
I've been _slowly_ working on version 5 and this is something I've taken into consideration. A solid black outline is probably too much, but here's what I've got at the moment: http://galen.in/mW3z

**Comment by tommygebru** [comment]
very nice @galengidman I really like it, but I am curious about how the interaction differs from the current site.
I really enjoy the mosiac of seeing all the brandcolors having different lengths/widths and primary or main colors.

**Comment by galengidman** [comment]
You'll be able to expand each brand for more detailed information: http://galen.in/H3Cb

**Comment by tommygebru** [comment]
That functionality and info is pretty good, but does the :focused color need to be very dark, can it be slightly grey?
Also I still think that the previous grid layout of a brandcolor is more "bold and authoritative",
so basically when you select a brandcolor and the pallete shape changes from a small circle to a large rectangle...
maybe its all the extra negative space thats bothering me, or that because the circles are small you dont get to appreciate the colors to much, with the rectangles they are much deeper
