### ISSUE TITLE
Brand Request: Cadbury

### ISSUE THREAD

**Issue by neko** [brandcolors/feedback#514]
- [x] *Brand Name*: Cadbury
- [x] *Brand Colors*: #482683, #FFFFFF, #1D1D1B
- [x] *Brand URL*: http://www.cadbury.co.uk/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: http://www.mwtr.com/~/media/Mwtr/com/PDF/Media/brandGuidelines/CadburylogoGuidelines1.pdf

**Comment by dkhamsing** [comment]
Submitted brand `1426` for review, thanks

**Comment by galengidman** [comment]
Published.
