### ISSUE TITLE
Brand Request: Algolia

### ISSUE THREAD

**Issue by LukyVj** [brandcolors/feedback#515]
- [x] *Brand Name*: Algolia
- [x] *Brand Colors*: 050F2C, 003666, 00AEFF, 3369E7, 8E43E7, B84592, FF4F81, FF6C5F, FFC168, 2DDE98, 1CC7D0
- [x] *Brand URL*: www.algolia.com
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: In our brand styleguide.

They look like this, in order : 
![](https://puu.sh/t4DNW/3b29fb0826.png)

**Comment by dkhamsing** [comment]
Submitted brand `1427` for review, thanks

**Comment by galengidman** [comment]
Published. Beautiful color scheme btw!
