### ISSUE TITLE
You should consider using vaunt.io

### ISSUE THREAD

**Issue by LukyVj** [brandcolors/feedback#516]
Hello, 

I just read your Readme, and I saw you do a sort of hand picking of the brand colors based on their logo. 

I know by experience that the color exctracted can be slightly different from the real one. 
That's why I think you should consider using http://vaunt.io/ ( which is a free images color extractor ) that will probably pick colors that are closer ( if not the same ) as the real one. 

You should consider adding this to your documentation. 

Regards, 
Lucas.

**Comment by galengidman** [comment]
You're right that color extracting is difficult and unreliable and I use it as a last resort when I'm finding and validating brand colors. I looked at Vaunt though, and unless I'm missing something, I think it would actually make the problem worse. It extracts the dominate (most used) colors from an image, but not the exact codes that the brand intended. A badly distorted JPG or even a PNG with a gradient would almost be guaranteed to be incorrect.

Am I missing something?

**Comment by LukyVj** [comment]
Hey!!

Nope you're right, I commented before testing,then I tested and yeah, I think it would make things worse indeed.

But the idea of using a tool to extract a color is still a thing to me :) 
Now, the question is : which tool

**Comment by galengidman** [comment]
I've found the color picker in Photoshop to the the most reliable when comparing what I pick out vs. what I _know_ the actual color is. FWIW.
