### ISSUE TITLE
Brand Request: Stack Exchange

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#519]
- [x] *Brand Name*: Stack Exchange
- [x] *Brand Colors*: 205296
- [x] *Brand URL*: http://stackexchange.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Lifted from the stylesheet of the SVG found [here](http://stackoverflow.com/company/logos).

The blues in the icon seem to just be shades of the main blue above but, for the sake of completeness, if you want to include them, they are:
- #90d8f5
- #4aa2da
- #356db6
- #1f5296

And the black is #010101.

**Comment by dkhamsing** [comment]
Submitted brand `1430` for review, thanks

**Comment by galengidman** [comment]
Thanks, published.
