### ISSUE TITLE
Boise State University

### ISSUE THREAD

**Issue by ryan-benson** [brandcolors/feedback#521]
- [X] *Brand Name*: Boise State University
- [X] *Brand Colors*: #09347A. #F1632A
- [X] *Brand URL*: boisestate.edu
- [x] *Updating brand* 
- [X] *Where/how you found the brand colors*: https://webguide.boisestate.edu/about-wordpress/web-colors-and-fonts/

**Comment by galengidman** [comment]
Already got it: https://brandcolors.net?brands=1434

**Comment by ryan-benson** [comment]
These are updated colors, my man. The first ones are conversions from the CMYK colors but they have specific hex codes recently listed.

**Comment by galengidman** [comment]
Ah, sweet. Updated.
