### ISSUE TITLE
Brand Request: Discogs

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#522]
- [x] *Brand Name*: Discogs
- [x] *Brand Colors*: 000, 333, fff, f5df2e
- [x] *Brand URL*: https://www.discogs.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From [their brand page](https://www.discogs.com/brand)

**Comment by galengidman** [comment]
Published.
