### ISSUE TITLE
Brand Request: MySQL

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#523]
- [x] *Brand Name*: MySql
- [x] *Brand Colors*: 0b7791, f3921f
- [ ] *Brand URL*: http://www.mysql.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: Lifted from the EPS files found [here](http://www.mysql.com/about/legal/logos.html). I used Photoshop so they may not be 100% correct, someone with Illustrator may be able to extract more accurate values.

**Comment by dkhamsing** [comment]
Submitted brand `1447` for review, thanks

**Comment by galengidman** [comment]
Published.
