### ISSUE TITLE
Brand Request: WWE

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#524]
- [x] *Brand Name*: World Wrestling Entertainment
- [x] *Brand Colors*: d7182a, fff, 232828
- [x] *Brand URL*: http://www.wwe.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Red & white lifted from [this SVG](http://www.wwe.com/a/i/wwe_logo.svg), black from website stylesheet.

**Comment by dkhamsing** [comment]
Submitted brand `1448` for review, thanks

**Comment by galengidman** [comment]
Published.
