### ISSUE TITLE
Bug with GET variables parsing

### ISSUE THREAD

**Issue by dgadelha** [brandcolors/feedback#525]
When passing `brands` as an array, a PHP warning is shown at the page:

`Warning: explode() expects parameter 2 to be string, array given in /srv/users/serverpilot/apps/brandcolors/public/wp-content/themes/brandcolors-4/index.php on line 70`

URL: https://brandcolors.net/?brands[]=1&brands[]=2

This can be solved with some extra condition like `if (isset($_GET["brands"]) and !is_array($_GET["brands"]))`
Or by simply disabling the PHP warnings, nothing much to care about.

**Comment by galengidman** [comment]
Thanks for sending this in. It'll be addressed in the next release.
