### ISSUE TITLE
Brand Request: FreeCodeCamp

### ISSUE THREAD

**Issue by tommygebru** [brandcolors/feedback#527]
- [ ] *Brand Name*:FreeCodeCamp
- [ ] *Brand Colors*: 006400,  FF9C2A, FF4025, 3949AB, EFEFEF
- [ ] *Brand URL*:https://www.freecodecamp.com
- [ ] *Updating brand* 
- [ ] *Where/how you found the brand colors*:https://www.freecodecamp.com/design-style-guide/

**Comment by dkhamsing** [comment]
Submitted brand `1459` for review, thanks

**Comment by galengidman** [comment]
Published.

**Comment by tommygebru** [comment]
Sweet! Many thanks
