### ISSUE TITLE
Update Colours: MailChimp

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#528]
- [x] *Brand Name*: [MailChimp](https://brandcolors.net?brands=380)
- [x] *Brand Colors*: 239ab9, 52bad5, 6dc5dc, 373737, 5d5c5d, b7b7b7
- [x] *Brand URL*: [mailchimp.com](https://mailchimp.com/)
- [x] *Updating brand*
- [x] *Where/how you found the brand colors*: On their [brand assets page](https://mailchimp.com/about/brand-assets/), where you can also download an [ASE file of their full palette](https://static.mailchimp.com/web/brand-assets/MailchimpOfficialColors.ase).

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
