### ISSUE TITLE
Duplicate Brand: Subway.

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#529]
There seems to be 2 entries for [Subway](https://brandcolors.net?brands=321,371) in the database, unless there's another company called Subway that I'm unaware of.

Neither set of colours looks quite right, though; I'm trying to find an official version of their brand guidelines to confirm.

**Comment by dkhamsing** [comment]
Hm oops

@galengidman can u check it out

I'm thinking we keep the second one for now

http://www.subway.com/

<img width="1407" alt="screen shot 2017-01-26 at 7 22 00 am" src="https://cloud.githubusercontent.com/assets/4723115/22336817/59543040-e398-11e6-803c-2363867f86c8.png">

![screen shot 2017-01-26 at 7 23 19 am](https://cloud.githubusercontent.com/assets/4723115/22336818/596b0a5e-e398-11e6-98c9-998f59b5182b.png)

**Comment by galengidman** [comment]
Good catch. I've kept the second one because it was sourced form the Subway Brand Style Guide: https://www.scribd.com/doc/88885955/Brand-Style-Guide
