### ISSUE TITLE
Brand Request: Shopmium

### ISSUE THREAD

**Issue by frboulais** [brandcolors/feedback#530]
- [x] *Brand Name*: Shopmium
- [x] *Brand Colors*: f01f74
- [x] *Brand URL*: https://www.shopmium.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Picked from source code (employee)

**Comment by galengidman** [comment]
Published.

**Comment by frboulais** [comment]
Thanks! Could you please replace "Shopium" by "Shopmium"? (it was a mistake) 👍

**Comment by dkhamsing** [comment]
@galengidman  can you help ?

**Comment by galengidman** [comment]
Fixed. Sorry about that mistake.
