### ISSUE TITLE
Brand request: Python

### ISSUE THREAD

**Issue by LuSo58** [brandcolors/feedback#531]
- [x] *Brand Name*: Python
- [x] *Brand Colors*: 366a96,3679b0,ffc836,ffe873,646464,2e597d
- [x] *Brand URL*: https://www.python.org/static/community_logos/python-powered-h.svg
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: The official Python site.

**Comment by galengidman** [comment]
Published.
