### ISSUE TITLE
Brand Request: Beats by Dre

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#532]
- [x] *Brand Name*: Beats by Dre
- [x] *Brand Colors*: f00
- [x] *Brand URL*: https://www.beatsbydre.com
- [ ] *Updating brand*
- [x] *Where/how you found the brand colors*: From [this SVG](https://ie.beatsbydre.com/on/demandware.static/Sites-beats-IE-Site/-/en_IE/v1483648029504/images/Logo_01.svg) used on their website.

**Comment by dkhamsing** [comment]
Submitted brand `1465` for review, thanks

**Comment by galengidman** [comment]
Hmm. The color they're using on their logo in the header is `#e01f3d`. I think I'll go with that. Thanks for sending this in.

**Comment by PeterShaggyNoble** [comment]
Strange; it looks like they have 2 shades of red - you can see `f00` in use on [their Irish site](http://ie.beatsbydre.com/), for example.
