### ISSUE TITLE
Update Colours: Booking.com

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#533]
- [x] *Brand Name*: Booking.com
- [x] *Brand Colors*: 003580, 009fe3, feba02, 666, f2F6fa
- [x] *Brand URL*: https://www.booking.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: From their [style guide](https://brand.booking.com/Styleguide/#page/0AFAA4FF-265A-465A-B17FA33CA481DCC4).

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
