### ISSUE TITLE
Brand Request: Visa

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#534]
- [x] *Brand Name*: Visa
- [x] *Brand Colors*: 1a1f71, f7b600
- [x] *Brand URL*: https://www.visa.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From a PDF in the ZIP file found on [this page](https://www.visaeurope.com/receiving-payments/pos_branding)

**Comment by dkhamsing** [comment]
Submitted brand `1466` for review, thanks

**Comment by galengidman** [comment]
Published.
