### ISSUE TITLE
Brand Request: Realex Payments

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#535]
- [x] *Brand Name*: Realex Payments
- [x] *Brand Colors*: f29023, 4d5255 OR f29024, 4e5356
- [x] *Brand URL*: https://www.realexpayments.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: The first pair are from the [SVG](https://www.realexpayments.com/wp-content/uploads/2015/06/rxp_logo1.svg) found on their main site while the second pair are from the [SVG](https://developer.realexpayments.com/assets/images/branding/realex/logo.svg) used on their [developers site](https://developer.realexpayments.com/) - I'm looking for their brand guidelines to try to determine which are the official colours but their is an EPS [here](http://www.realexpayments.com/images/logos/mlogos/realex-logo.eps) that might help you clarify things.

**Comment by dkhamsing** [comment]
@PeterShaggyNoble 
Hm I see the orange there, but how about the blue ?

**Comment by galengidman** [comment]
I published this with just `#f29023` and `#4d5255` since those seemed to be the primary.
