### ISSUE TITLE
Update Colours: Zendesk

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#536]
- [x] *Brand Name*: Zendesk
- [x] *Brand Colors*: 00363d, f79a3e, eb6651, 30aabc, eb4962, 37b8af, 78a300, f0ca28
- [x] *Brand URL*: https://www.zendesk.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: From the SVGs contained in the [ZIP file](https://d1eipm3vz40hy0.cloudfront.net/images/company/Zendesk-brand-assets.zip) found on [this page](https://www.zendesk.com/company/brand-assets/).

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
