### ISSUE TITLE
Update Colours: Hulu

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#537]
- [x] *Brand Name*: Hulu
- [x] *Brand Colors*: 6a3, 9c3, 41811e, 222, 666, e8e8e8
- [x] *Brand URL*: https://www.hulu.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: On [this page](https://www.hulu.com/press/assets)

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Published.
