### ISSUE TITLE
Brand Request: Adidas Originals

### ISSUE THREAD

**Issue by lilznk** [brandcolors/feedback#538]
- [x] *Brand Name*: Adidas Originals
- [x] *Brand Colors*: 0078c1,000000,ffffff
- [x] *Brand URL*: http://www.adidas.com/originals
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: Their Logo(s).
![adidas-originals](https://cloud.githubusercontent.com/assets/25316119/22539360/d8fc29de-e919-11e6-8d61-cd46edfff055.gif)

**Comment by dkhamsing** [comment]
@galengidman should we also add regular adidas colors ? (looks like black and white)

**Comment by lilznk** [comment]
The regular one is only Black (#000000) & White (#ffffff) :)

**Comment by galengidman** [comment]
I've added Adidas proper, but going to leave off this sub-brand for now.
