### ISSUE TITLE
Brand Request: Puma

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#539]
- [x] *Brand Name*: Puma
- [x] *Brand Colors*: 000,44403f,696965,ba2026,ae946d,fff
- [x] *Brand URL*: http://puma.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://mariastegemeyer.files.wordpress.com/2016/03/puma-brand-guidelines1.pdf.

**Comment by dkhamsing** [comment]
Submitted brand `1469` for review, thanks

**Comment by dkhamsing** [comment]
@PeterShaggyNoble thanks for all the additions, can you keep the color format to:
`000,44403f,696965` no spaces
instead of
`000, 44403f, 696965`

cheers!

**Comment by PeterShaggyNoble** [comment]
Can do - will update all my open issues now.

**Comment by galengidman** [comment]
Published.
