### ISSUE TITLE
Update Colours: Alienware

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#540]
- [x] *Brand Name*: Alienware
- [x] *Brand Colors*: 0c3866,49c0b6,222,ce181e,007cc0,ffc20e
- [x] *Brand URL*: http://www.dell.com/en-us/gaming/alienware?cs=19
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/design.st.ch/docs/alienware_brand_guide_2016_pages.

There are also 3 other colours (see p.12) that they only supply Pantones for; don't know how you usually sample those.

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
