### ISSUE TITLE
Brand Request: Aer Lingus

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#541]
- [x] *Brand Name*: Aer Lingus
- [x] *Brand Colors*: 008374,89ba16,fefefe
- [x] *Brand URL*: https://www.aerlingus.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/lukaszkulakowski/docs/aerlingus_brand_identity_system_gui.

**Comment by dkhamsing** [comment]
Submitted brand `1469` for review, thanks

**Comment by dkhamsing** [comment]
Submitted brand `1471` for review, thanks

**Comment by galengidman** [comment]
Published.
