### ISSUE TITLE
Brand Request: Ryanair

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#542]
- [x] *Brand Name*: Ryanair
- [x] *Brand Colors*: 073590,f1c933,2091eb *Secondary:* 0d49c0,062b71,cdd7e9,2e2e2e,aeb3bd,f4f4f4
- [x] *Brand URL*: https://www.ryanair.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://www.behance.net/gallery/34224289/Ryanair-Design-Centre.

**Comment by dkhamsing** [comment]
Submitted brand `1472` (primary colors) for review, thanks

**Comment by galengidman** [comment]
Published.
