### ISSUE TITLE
Brand Request: NFL

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#543]
- [x] *Brand Name*: NFL
- [x] *Brand Colors*: 013369,d50a0a,fff
- [x] *Brand URL*: http://www.nfl.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/janjaneczek/docs/nfl, using the RGB values provided.

**Comment by dkhamsing** [comment]
Submitted brand `1470` for review, thanks

**Comment by galengidman** [comment]
Published.
