### ISSUE TITLE
Brand Request: Sage

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#546]
- [x] *Brand Name*: Sage
- [x] *Brand Colors*: fff,007f64,41a940,4d4f53,9a9b9c,e0e1dd *Secondary:* ff5800,009fda,6639b7
- [x] *Brand URL*: http://www.sage.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/bondo/docs/sage_visual_identity_guidelines.

**Comment by galengidman** [comment]
Published.
