### ISSUE TITLE
Duplicate Brand: Princeton

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#547]
There are [2 entries](https://brandcolors.net?brands=1292,1443) on the site for Princeton, both with the same colour and, although it's not much of a difference, according to [this document](https://issuu.com/janjaneczek/docs/pu-identity-guide-20081027), that colour should be `ee7f2d`.

**Comment by dkhamsing** [comment]
oops! thx for letting us know

**Comment by galengidman** [comment]
Fixed.
