### ISSUE TITLE
Brand Request/Discussion: Channel 4

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#549]
- [x] *Brand Name*: Channel 4
- [x] *Brand Colors*: ffd611,d1091e,63cbc6,6d2d83,009540,1c3d74,ec008c,85b7e3,fff
- [x] *Brand URL*: http://www.channel4.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: The colours above are the primary colours used in the [SVG logo](http://static.channel4.com/globalnavv1/1.0.376/images/header-logo.svg) on their website. However, I also found http://www.channel4.com/about_c4/styleguide/downloads/C4StyleGuide1.1.pdf which lists a lot more colours (see p.11), some of them variants of the ones above. I suspect the PDF may be out of date but have included it in case I'm wrong. Their current style guide, found [here](http://styleguides.channel4.com/), doesn't seem to contain an details on colours.

**Comment by dkhamsing** [comment]
Submitted brand `1474` for review, thanks

**Comment by galengidman** [comment]
I went ahead with what was in the styleguide. Thanks for submitting.
