### ISSUE TITLE
Brand Request: Sony

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#552]
- [x] *Brand Name*: Sony
- [x] *Brand Colors*: 000
- [x] *Brand URL*: http://www.sony.com/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/janjaneczek/docs/2008_style_guide_final. The document also includes a load of other colours (see p.34) but says they're for "subtle highlights" only so I don't know if they should be included.

**Comment by galengidman** [comment]
Published.
