### ISSUE TITLE
Update Colours: Heineken

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#553]
- [x] *Brand Name*: Heineken
- [x] *Brand Colors*: 008200,205527,ff2b00,c3c3c3
- [x] *Brand URL*: http://www.heineken.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://issuu.com/bondo/docs/hnv_guidelines_12.2011_v3.

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by dkhamsing** [comment]
@PeterShaggyNoble instead of linking with "this document", can you just paste the url so we can see what it is right away?

i.e.
> From https://issuu.com/bondo/docs/hnv_guidelines_12.2011_v3

**Comment by PeterShaggyNoble** [comment]
Yep, will do - I've updated all my open issues to make that change.

**Comment by galengidman** [comment]
Published.
