### ISSUE TITLE
Brand Request: NASA

### ISSUE THREAD

**Issue by PeterShaggyNoble** [brandcolors/feedback#554]
- [x] *Brand Name*: NASA
- [x] *Brand Colors*: fc3d21,0b3d91
- [x] *Brand URL*: https://www.nasa.gov/
- [ ] *Updating brand* 
- [x] *Where/how you found the brand colors*: From https://sservi.nasa.gov/wp-content/uploads/2011/10/NASA_Style_Guide_v2.1.pdf.

**Comment by dkhamsing** [comment]
Submitted brand `1476` for review, thanks

**Comment by shetyeshail** [comment]
I think those hex values are actually incorrect, they should be:
Red (Pantone 185): #E4002B
Blue (Pantone 286): #0033A0

Other colors include:
Pantone Cool Grey 9: #75787B
Pantone 877: #8A8D8F
Pantone Black 6: #101820

**Comment by dkhamsing** [comment]
We'll need @galengidman for this

**Comment by galengidman** [comment]
The NASA PDF lists exact RGB (another form of HEX) color values, so I feel pretty good about what we have. Thanks for taking the time to look into this though.

**Comment by dkhamsing** [comment]
@galengidman hey this has not bee published.. can you take a look

![screen shot 2017-06-13 at 1 47 19 pm](https://user-images.githubusercontent.com/4723115/27103828-dd29cda4-503e-11e7-9054-a395d49c8485.png)

**Comment by galengidman** [comment]
My b. I thought it had been published. Now it is!
