### ISSUE TITLE
Brand Request: State Farm

### ISSUE THREAD

**Issue by BoredFish** [brandcolors/feedback#555]
- [x] *Brand Name*: State Farm
- [x] *Brand Colors*: CC0717
- [x] *Brand URL*: www.StateFarm.com
- [x] *Where/how you found the brand colors*: www.statefarmbrandcenter.com

**Comment by dkhamsing** [comment]
Submitted brand `1477` for review, thanks

**Comment by galengidman** [comment]
Published.
