### ISSUE TITLE
Brand Request: Zomato!!

### ISSUE THREAD

**Issue by koetsuji** [brandcolors/feedback#557]
- [ ] *Brand Name*:
- [ ] *Brand Colors*:
- [ ] *Brand URL*:
- [ ] *Where/how you found the brand colors*:

**Comment by PeterShaggyNoble** [comment]
From https://www.zomato.com/content_guidelines.pdf, their colours are: cb202d,2d2d2d,fff,f4f4f2.

**Comment by dkhamsing** [comment]
Zomato is already on brand colors, @galengidman can you see if it needs an update?

**Comment by galengidman** [comment]
Yup, I added it this morning and forgot to follow up on this issue.
