### ISSUE TITLE
Brand request: Taiga

### ISSUE THREAD

**Issue by Xaviju** [brandcolors/feedback#559]
- [x] Brand Name*: Taiga
- [x] Brand Colors*: 444444, b8b8b8, 72a114, 9dce0a, 879b89
- [x] Brand URL*: http://taiga.io
- [x] Where/how you found the brand colors*: I'm a Taiga developer myself. Design (and used colors) are here: https://github.com/taigaio/taiga-design

---

*edited*

**Comment by galengidman** [comment]
When you say you found these on Google, what do you mean by that?

**Comment by Xaviju** [comment]
@galengidman Sorry, my mistake while writting the issue!

**Comment by galengidman** [comment]
Published
