### ISSUE TITLE
Texas Tech University

### ISSUE THREAD

**Issue by jreina** [brandcolors/feedback#560]
- [x] *Brand Name*: Texas Tech University
- [x] *Brand Colors*: cc0000,000000
- [x] *Brand URL*: http://www.ttu.edu/
- [x] *Where/how you found the brand colors*: https://www.depts.ttu.edu/communications/identityguidelines/idguidelines/ttu/elements/color.php

**Comment by galengidman** [comment]
Added. Thanks!
