### ISSUE TITLE
Brand Request: MongoDB

### ISSUE THREAD

**Issue by TheExeLab** [brandcolors/feedback#561]
- [ ] *Brand Name*: MongoDB
- [ ] *Brand Colors*: f5f6f7, 589636, 7fc857, 6aaf4e, 4d4d4d, 353535
- [ ] *Brand URL*: https://MongoDB.com
- [ ] *Where/how you found the brand colors*: Website and logo resources

**Comment by dkhamsing** [comment]
@TheExeLab do you have a link to the website and logo resources?

**Comment by dkhamsing** [comment]
Submitted brand `530` for review, thanks

**Comment by galengidman** [comment]
@TheExeLab Did you pull these colors from the logo, or were they listed somewhere?

**Comment by TheExeLab** [comment]
@galengidman Extracted from logo and website

**Comment by galengidman** [comment]
I've decided to with just one green vs the 4 different shades used in the logo. Published.
