### ISSUE TITLE
Brand Request: Blockchain

### ISSUE THREAD

**Issue by jerboa88** [brandcolors/feedback#562]
- [x] *Brand Name*: Blockchain
- [x] *Brand Colors*: 00aee6, 123962, 799eb2, 2754ba, b1d4e5, ffffff
- [x] *Brand URL*: https://www.blockchain.com/ or https://blockchain.info/
- [x] *Where/how you found the brand colors*: All colors grabbed from the logo. The same colors are used on the site as well.

**Comment by dkhamsing** [comment]
Submitted brand `533` for review, thanks

**Comment by galengidman** [comment]
Published.
