### ISSUE TITLE
Brand Request: Rowan University

### ISSUE THREAD

**Issue by Gunny123** [brandcolors/feedback#564]
Brand Request: Rowan University

- [x] *Brand Name*: Rowan University
- [x] *Brand Colors*: 3F1A0A, EDD51C
- [x] *Brand URL*: rowan.edu
- [x] *Where/how you found the brand colors*: [Rowan University's Graphic Standards Page](http://www.rowan.edu/universityrelations/publications/colors/)

**Comment by galengidman** [comment]
Published.
