### ISSUE TITLE
Brand Request: University of Alberta

### ISSUE THREAD

**Issue by jerboa88** [brandcolors/feedback#565]
- [x] *Brand Name*: University of Alberta
- [x] *Brand Colors*: 007c41, ffdB05, fbed80, fdf3b4
- [x] *Brand URL*: http://ualberta.ca
- [x] *Where/how you found the brand colors*: http://www.toolkit.ualberta.ca/VisualIdentityGuidelines/OurColours.aspx. The last two colors were grabbed from the logo.

**Comment by galengidman** [comment]
Published.
