### ISSUE TITLE
Brand Request: LocalBitcoins

### ISSUE THREAD

**Issue by jerboa88** [brandcolors/feedback#566]
- [x] *Brand Name*: LocalBitcoins
- [x] *Brand Colors*: 00599e, e77817
- [x] *Brand URL*: https://localbitcoins.com
- [x] *Where/how you found the brand colors*: Logo (https://3.bp.blogspot.com/-ynu9YoINA48/Ua2xWIYLQXI/AAAAAAAAABk/oOukJ45n6UY/s1600/LocalBitcoins.com%2BLogo%2Bcropped.png)

Sorry for all the requests, guys.

**Comment by galengidman** [comment]
Published.
