### ISSUE TITLE
Brand Request: Raspberry Pi

### ISSUE THREAD

**Issue by FlyteWizard** [brandcolors/feedback#567]
- [X] *Brand Name*: Raspberry Pi
- [X] *Brand Colors*: 83c55c, c91e4a
- [X] *Brand URL*: https://www.raspberrypi.org/
- [X] *Where/how you found the brand colors*: Logo (https://www.raspberrypi.org/wp-content/uploads/2012/03/raspberry-pi-logo.png)

**Comment by PeterShaggyNoble** [comment]
Per their visual identity guidelines (https://www.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines.pdf), their colours are c7053d and 8cc04b.

**Comment by dkhamsing** [comment]
Submitted brand `536` for review, thanks

**Comment by galengidman** [comment]
Published.
