### ISSUE TITLE
Brand Request: University of Victoria

### ISSUE THREAD

**Issue by FlyteWizard** [brandcolors/feedback#568]
- [X] *Brand Name*: University of Victoria
- [X] *Brand Colors*: 005493, F5AA1C, C63527, 002754
- [X] *Brand URL*: http://www.uvic.ca/
- [X] *Where/how you found the brand colors*: (http://www.uvic.ca/brand/look-feel/colour/palette/index.php)

**Comment by galengidman** [comment]
Published.
