### ISSUE TITLE
Continental AG

### ISSUE THREAD

**Issue by superfine** [brandcolors/feedback#569]
- [x] *Brand Name*: Continental AG
- [x] *Brand Colors*: ffa500,000000,ffffff,737373,969696,cdcdcd,f0f0f0,00a5dc,004eaf,2db928,057855,ff2d37
- [x] *Brand URL*: http://www.continental-corporation.com/
- [x] *Where/how you found the brand colors*: http://www.designtagebuch.de/cd-manuals/Continental_Corporate_Design.pdf (Page 35)

**Comment by dkhamsing** [comment]
Submitted brand `538` for review, thanks

**Comment by galengidman** [comment]
Published.
