### ISSUE TITLE
Brand Request: Alibaba

### ISSUE THREAD

**Issue by dtwen** [brandcolors/feedback#570]
- [x] *Brand Name*: Alibaba
- [x] *Brand Colors*:  #FC6A21
- [x] *Brand URL*: https://www.alibaba.com
- [x] *Where/how you found the brand colors*: I used [Frank DeLoupe](http://jumpzero.com/frank/) tool to color pick it from their site.

BABA (NYSE) is a $269B e-commerce company in China that is the world's largest retailer.  I saw your site had WeChat and Baidu so figured this is a natural fit.

**Comment by dkhamsing** [comment]
Submitted brand `540` for review, thanks

**Comment by galengidman** [comment]
Published.
