### ISSUE TITLE
UPS brand

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#573]
- [ ] *Brand Name*: UPS
- [ ] *Brand Colors*: 351C15,FFB500
- [ ] *Brand URL*: https://www.upsbrandexchange.com/brUpsCarbonNeutral.awsp
- [ ] *Where/how you found the brand colors*: UPS website

**Comment by dkhamsing** [comment]
Submitted brand `552` for review, thanks

**Comment by galengidman** [comment]
Published.
