### ISSUE TITLE
Royal Mail Post

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#575]
- [ ] *Brand Name*: Royal Mail
- [ ] *Brand Colors*: FF0000, FFFF00, 000000,	FFFFFF
- [ ] *Brand URL*: http://www.royalmail.com/
- [ ] *Where/how you found the brand colors*: http://www.royalmail.com/sites/default/files/docs/pdf/Logo_guidelines.pdf

---

*edited*

**Comment by dkhamsing** [comment]
Submitted brand `556` for review, thanks

**Comment by galengidman** [comment]
Published.
