### ISSUE TITLE
Brand Request: Arriva

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#578]
- [x] *Brand Name*: Arriva
- [x] *Brand Colors*: 004d73, 00334e, 007fdb, dbebfa, 832561, 11862f, bfca02, 848a8c
- [x] *Brand URL*: http://brandingmanual.com/arrivadk/460-corporate-colors/
- [x] *Where/how you found the brand colors*: corporate colors link

**Comment by galengidman** [comment]
Published.
