### ISSUE TITLE
Brand Request: Veolia

### ISSUE THREAD

**Issue by riay388** [brandcolors/feedback#579]
- [x] *Brand Name*: Veolia
- [x] *Brand Colors*: ed1c24
- [x] *Brand URL*: www.veolia-transport.com
- [x] *Where/how you found the brand colors*: from company logo svg

**Comment by galengidman** [comment]
Going to pass on this one. Thanks for submitting.

**Comment by riay388** [comment]
why are you passing on it?

**Comment by galengidman** [comment]
This appears to be a fairly low-traffic, recently launched car blog. I don't think it's yet at the stage where it would be a relevant and helpful addition to the collection.

**Comment by riay388** [comment]
Ah ok. I understand that.
