### ISSUE TITLE
Brand Request: Carrot

### ISSUE THREAD

**Issue by ayezee33** [brandcolors/feedback#580]
- [x] *Brand Name:* Carrot:
- [x] *Brand Colors:* #388ed1,  #d74e26,  #006837,  #fa9f1e,  #f7931e:
- [x] *Brand URL:* https://oncarrot.com/:
- [x] *Where/how you found the brand colors* I am a designer at Carrot and our colors are published here https://oncarrot.com/branding/:

**Comment by galengidman** [comment]
Published.
