### ISSUE TITLE
Brand Request: Stockton University

### ISSUE THREAD

**Issue by Gunny123** [brandcolors/feedback#583]
- [x] *Brand Name*: Stockton University
- [x] *Brand Colors*: 000000, 79bde9, ffffff, ffc423, bc9b6a, a7a9ac (All 6 are primary)
- [x] *Brand URL*: [Stockton University Homepage](https://www.stockton.edu/)
- [x] *Where/how you found the brand colors*: [Stockton University Brand Guide PowerPoint Presentation, Slide 24-25](http://fliphtml5.com/ivrx/birc/basic)

**Comment by galengidman** [comment]
Published.
