### ISSUE TITLE
Brand Request: Seton Hall University

### ISSUE THREAD

**Issue by Gunny123** [brandcolors/feedback#584]
- [x] *Brand Name*: Seton Hall University
- [x] *Brand Colors*: 0004488, ffffff
- [x] *Brand URL*: [Seton Hall Homepage](https://www.shu.edu/)
- [x] *Where/how you found the brand colors*: [Brand Guidelines page 4](https://www13.shu.edu/offices/technology/upload/graphics-manual.pdf)

**Comment by galengidman** [comment]
Published.
