### ISSUE TITLE
Brand Request: Montclair State University

### ISSUE THREAD

**Issue by Gunny123** [brandcolors/feedback#585]
- [x] *Brand Name*: Montclair State University
- [x] *Brand Colors*: Primary: 000000, CE1141, 
                                   Secondary: EEB111, E87D1E, 94CE08, 00386B, 969491
- [x] *Brand URL*: [Montclair State University](http://www.montclair.edu/)
- [x] *Where/how you found the brand colors*: [Montclair State University Color Palette](http://www.montclair.edu/its-all-here/brand-manual/color-palette/)

**Comment by galengidman** [comment]
Published.
