### ISSUE TITLE
Brand Request: The College of New Jersey

### ISSUE THREAD

**Issue by Gunny123** [brandcolors/feedback#586]
- [x] *Brand Name*: The College of New Jersey 
- [x] *Brand Colors*: 293f6f, a67a00 (Converted from RGB 41,63, 111 and RGB 166, 122, 0)
- [x] *Brand URL*: [TCNJ Homepage](http://tcnj.pages.tcnj.edu/)
- [x] *Where/how you found the brand colors*: [Logo/Font Usage Page](http://www.tcnjathletics.com/sports/2013/12/5/GEN_1205133829.aspx?id=1449)

**Comment by galengidman** [comment]
Published.
