### ISSUE TITLE
Redox | The Modern API for Healthcare

### ISSUE THREAD

**Issue by cravelight** [brandcolors/feedback#587]
- [x] *Brand Name*: REDOX
- [x] *Brand Colors*: 0a2239,01b287,ff9f1c,e5505a,854c9e
- [x] *Brand URL*: https://www.redoxengine.com/
- [x] *Where/how you found the brand colors*: Image posted by Redox design team on slack channel.

<img width="302" alt="redoxbrandcolors" src="https://cloud.githubusercontent.com/assets/543163/25155268/cffa0c36-2459-11e7-8f9d-88f4c35db57f.png">

**Comment by galengidman** [comment]
Published.
