### ISSUE TITLE
Brand Request: Gogo, LLC

### ISSUE THREAD

**Issue by davidmiazga** [brandcolors/feedback#588]
- [x] *Brand Name*: Gogo
- [x] *Brand Colors*: #e80029, #40b4e5, #7c868d
- [x] *Brand URL*: https://www.gogoair.com/
- [x] *Where/how you found the brand colors*: I work at Gogo in the creative dept.

---

*edited*

**Comment by dkhamsing** [comment]
Submitted brand `565` for review, thanks

**Comment by galengidman** [comment]
Published.

**Comment by davidmiazga** [comment]
Thank you. Much appreciated. 

    On Wednesday, April 19, 2017 11:38 AM, Galen Gidman <notifications@github.com> wrote:
 

 Closed #588.—
