### ISSUE TITLE
Brand Request: livinplay

### ISSUE THREAD

**Issue by manureggi** [brandcolors/feedback#589]
- [x] *Brand Name*: livinplay
- [x] *Brand Colors*: e6431d, 000000
- [x] *Brand URL*: [www.livinplay.com](http://www.livinplay.com)
- [x] *Where/how you found the brand colors*: I represent this brand

**Comment by galengidman** [comment]
This brand doesn't appear to have grown to the level of notoriety where it's ready for BrandColors yet. I really appreciate you taking the time to submit though.
