### ISSUE TITLE
eBazaarShop

### ISSUE THREAD

**Issue by islamzatary** [brandcolors/feedback#593]
- [x] *Brand Name*: eBazaarShop
- [x] *Brand Colors*: #3498db
- [x] *Brand URL*: https://www.ebazaarshop.com/
- [x] *Where/how you found the brand colors*: owner

**Comment by galengidman** [comment]
Hi Islam

Thanks for taking the time to submit this. Looking at eBazaarShop, I'm not sure it's a prominent enough brand yet that I feel it would fit well on BrandColors.

Thanks,
— Galen
