### ISSUE TITLE
Ruby on Rails

### ISSUE THREAD

**Issue by skunkworker** [brandcolors/feedback#594]
- [x] *Brand Name*: Ruby on Rails
- [x] *Brand Colors*: cc0000, 000000
- [x] *Brand URL*: http://rubyonrails.org/
- [x] *Where/how you found the brand colors*: http://rubyonrails.org/images/rails-logo.svg

---

*edited*

**Comment by dkhamsing** [comment]
Submitted brand `584` for review, thanks

**Comment by skunkworker** [comment]
@dkhamsing  Whoops I made a mistake, the brand colors should be `cc0000, ffffff` Red and white, not red and black.

**Comment by dkhamsing** [comment]
@skunkworker updated :)

**Comment by galengidman** [comment]
Published.
