### ISSUE TITLE
Functional Tennis

### ISSUE THREAD

**Issue by fabmol** [brandcolors/feedback#597]
- [ ] *Brand Name*:Functional Tennis
- [ ] *Brand Colors*:00adef
- [ ] *Brand URL*:www.functionaltennis.com
- [ ] *Where/how you found the brand colors*: color pick from hi res logo

**Comment by galengidman** [comment]
Thanks for taking the time to submit. I'm going to pass on this for now — not sure it's the type of brand I'm looking for.
