### ISSUE TITLE
Brand Request: Box

### ISSUE THREAD

**Issue by abjerner** [brandcolors/feedback#601]
- [X] *Brand Name*: Box
- [X] *Brand Colors*: 0061d5
- [X] *Brand URL*: https://www.box.com/
- [X] *Where/how you found the brand colors*: CSS fill of SVG logo - eg. found here: https://www.box.com/en-gb/file-sharing

**Comment by dkhamsing** [comment]
Submitted brand `598` for review, thanks

**Comment by galengidman** [comment]
Published.
