### ISSUE TITLE
Temple University

### ISSUE THREAD

**Issue by shetyeshail** [brandcolors/feedback#602]
- [ ] *Brand Name*: Temple University
- [ ] *Brand Colors*: Primary: #a41e35, #222222, #899197 Secondary: #8c2132, #ee2738, #ae872d, #c1d62e, #e20f84, #9c268f, #fcb426, #90d1bb, #6ec4e8, #007bc2, #767a4c
- [ ] *Brand URL*: [http://www.temple.edu](http://www.temple.edu)
- [ ] *Where/how you found the brand colors*: [http://branding.temple.edu/brand-guidelines](http://branding.temple.edu/brand-guidelines)

**Comment by galengidman** [comment]
Published.

**Comment by pixelyunicorn** [comment]
Thank you @shetyeshail! I was wondering who added it to brandcolors and figured it would be you :+1:

**Comment by shetyeshail** [comment]
Yep of course haha. I added SEPTA too and am probably going to do a few others eventually.
