### ISSUE TITLE
Brand Request:  Clemson University

### ISSUE THREAD

**Issue by jlarmstrongiv** [brandcolors/feedback#603]
- [x] *Brand Name*:  Clemson University
- [x] *Brand Colors*:  F66733,522D80,FFFFFF,D4C99E,685C53,A25016,562E19,86898C,F9E498,566127,3A4958,B5C327,109DC0,000000
- [x] *Brand URL*:  http://www.clemson.edu/
- [x] *Where/how you found the brand colors*:  https://www.clemson.edu/brand/guide/color.html

**Comment by galengidman** [comment]
Published.
