### ISSUE TITLE
SEPTA

### ISSUE THREAD

**Issue by shetyeshail** [brandcolors/feedback#604]
- [ ] *Brand Name*: SEPTA (Southeastern Pennsylvania Transportation Authority)
- [ ] *Brand Colors*: Main Logo Colors: F9423A, 001489, FFFFFF; Broad Street Line: F56600; Market-Frankfort Line: 0072CE; Warning Signs: FFD100, E4002B, C8102E, 418FDE
- [ ] *Brand URL*: [www.septa.org](http://www.septa.org/)
- [ ] *Where/how you found the brand colors*: [http://www.septa.org/business/bid/100k/detail/File%203%20-%20Specifications_15-00171-AMZK_Suburban%20Station.pdf](http://www.septa.org/business/bid/100k/detail/File%203%20-%20Specifications_15-00171-AMZK_Suburban%20Station.pdf) on page

**Comment by galengidman** [comment]
Published.
