### ISSUE TITLE
Brand Request: NaNoWriMo Young Writers Program

### ISSUE THREAD

**Issue by brandonmack111** [brandcolors/feedback#606]
- [x] *Brand Name*: NaNoWriMo Young Writers Program
- [x] *Brand Colors*: 39bfc2, 2c3537, ffffff
- [x] *Brand URL*: https://ywp.nanowrimo.org
- [x] *Where/how you found the brand colors*: logo, colors sampled with GIMP

**Comment by galengidman** [comment]
Adding NaNoWriMo, but passing on this one.
