### ISSUE TITLE
Brand Request: Camp NaNoWriMo

### ISSUE THREAD

**Issue by brandonmack111** [brandcolors/feedback#607]
- [x] *Brand Name*: Camp NaNoWriMo
- [x] *Brand Colors*: 0397d6, 003e7e, ffffff
- [x] *Brand URL*: https://campnanowrimo.org
- [x] *Where/how you found the brand colors*: logo, colors sampled with GIMP

**Comment by galengidman** [comment]
NaNoWriMo will be added, but I think this is probably one I'll pass on.
