### ISSUE TITLE
Brand Request: Brand Colors (you don't have your own brand listed - is that intentional?)

### ISSUE THREAD

**Issue by brandonmack111** [brandcolors/feedback#608]
- [x] *Brand Name*: Brand Colors
- [x] *Brand Colors*: ef3981, e92767, e91e63, e1134b, d9e559, ccdb42, cddc39, bdd027, 3eadf6, 2b97f2, 2196f3, 157dee, b245c2, 9c31af, 9c27b0, 84199a (but I'm guessing you already knew that)
- [x] *Brand URL*: https://brandcolors.net/
- [x] *Where/how you found the brand colors*: https://brandcolors.net/assets/img/logo.png, sampled with GIMP.

I mainly submitted this because I think it only makes sense that your own brand would be on your website - but I didn't see it.

**Comment by galengidman** [comment]
Hmm. That's an interesting thought, but I don't really see those as being very useful? FWIW, I think I sampled those from the Material Design color scheme: https://material.io/guidelines/style/color.html
