### ISSUE TITLE
Brand Request: downinthep.it

### ISSUE THREAD

**Issue by ryan-benson** [brandcolors/feedback#610]
- [X] *Brand Name*: downinthep.it
- [X] *Brand Colors*: 222222, EF4949
- [x] *Brand URL*: http://downinthep.it
- [X] *Where/how you found the brand colors*: Team member

**Comment by galengidman** [comment]
Hi Ryan.

downinthep.it looks like a great resource for music news, but probably doesn't have the level of brand awareness that we're looking for for BrandColors. Thanks for taking the time to submit though.
