### ISSUE TITLE
Proposal: Hue filtering

### ISSUE THREAD

**Issue by octaharon** [brandcolors/feedback#612]
The first obvious thing I miss from this website is looking for all brands having a particular hue (within some range). This could be useful when looking for palette cases when you have one or two primary colors and want to find good complementaries

This could be done as a simple hue stripe popped up with a colorful button next to looking glass icon on top. If you find this idea nice, I can help you implementing it within frontend or can provide you with a standalone module

**Comment by galengidman** [comment]
Appreciate the thought. More advanced color filtering is something that's been suggested before and I may work towards implementing in the future. I'm going to close this for now, but tag it for possible use later.
