### ISSUE TITLE
New colors of Patreon

### ISSUE THREAD

**Issue by kevinhaendel** [brandcolors/feedback#613]
- [x] *Brand Name*: Patreon
- [x] *Brand Colors*: f96854,052d49
- [x] *Brand URL*: https://www.patreon.com
- [x] *Where/how you found the brand colors*: https://www.patreon.com/brand/guidelines

**Comment by dkhamsing** [comment]
Thank you, this update will require @galengidman's help

**Comment by galengidman** [comment]
Updated.
