### ISSUE TITLE
barclays bank

### ISSUE THREAD

**Issue by amitauti** [brandcolors/feedback#614]
- [ X] *Barclays*:
- [ ] *Brand Colors*:
- [ ] http://www.barclays.co.uk/
- [ ] *Where/how you found the brand colors*:

---

*edited*

**Comment by dkhamsing** [comment]
Do u have the color codes?

**Comment by amitauti** [comment]
here you go - 00AFE9

**Comment by dkhamsing** [comment]
Submitted brand `621` for review, thanks

**Comment by galengidman** [comment]
Live. Thanks!
