### ISSUE TITLE
Brand Colors For Oregon State University

### ISSUE THREAD

**Issue by halfsail** [brandcolors/feedback#615]
- [Oregon State University ] *Brand Name*:
- [DC4405, 000000, FFFFFF ] *Brand Colors*:
- [http://communications.oregonstate.edu/brand-guide] *Brand URL*:
- [http://communications.oregonstate.edu/brand-guide/visual-identity/colors ] *Where/how you found the brand colors*:

**Comment by dkhamsing** [comment]
Submitted brand `625 ` for review, thanks

**Comment by galengidman** [comment]
Published
