### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by DavydeVries** [brandcolors/feedback#617]
- [x] *Brand Name*: Postman
- [x] *Brand Colors*: ef5b25
- [x] *Brand URL*: https://www.getpostman.com/
- [x] *Where/how you found the brand colors*: source code of primary buttons on the site. (They don't have a press kit.)

**Comment by dkhamsing** [comment]
Postman is already on BrandColors

![](http://i.imgur.com/FFCG0dC.png)



Thanks!
