### ISSUE TITLE
Brand Request : DemonWolfDev

### ISSUE THREAD

**Issue by MrDemonWolf** [brandcolors/feedback#618]
- [x] *Brand Name*: DemonWolfDev
- [x] *Brand Colors*: 050240,2f2f2f,ffffff
- [x] *Brand URL*: www.demonwolfdev.com
- [x] *Where/how you found the brand colors*: I am the Owner of the company. They can also be found [here](https://assets.demonwolfdev.com/)

**Comment by galengidman** [comment]
Thanks for submitting this. It's a policy of BrandColors to not publish design/dev studio colors since they're rarely of use to anyone but the owner of the studio, so I'll have to pass on these.

Still, thanks again for taking the time to submit.
