### ISSUE TITLE
Dailymotion Brand Color

### ISSUE THREAD

**Issue by creativejuiz** [brandcolors/feedback#619]
- [x] *Brand Name*: Dailymotion
- [x] *Brand Colors*: 00AAFF, 00D2F3, FFFFFF, 000000
- [x] *Brand URL*: http://dailymotion.com/
- [ ] *Where/how you found the brand colors*: http://press.dailymotion.com/?page_id=346 (404 :/)

**Comment by dkhamsing** [comment]
Submitted brand `638` for review, thanks

**Comment by galengidman** [comment]
Published.
