### ISSUE TITLE
Brand request: Mimesia

### ISSUE THREAD

**Issue by acjbizar** [brandcolors/feedback#620]
- [x] *Brand Name*: Mimesia
- [x] *Brand Colors*: #2269ca
- [x] *Brand URL*: http://mimesia.com/
- [x] *Where/how you found the brand colors*: I am the founder. The color has its own website, which provides a tiny bit of history: http://mimesia.blue/.

**Comment by galengidman** [comment]
Going to pass on this. Thanks for taking the time to submit.
