### ISSUE TITLE
Brand suggestion: Dalim

### ISSUE THREAD

**Issue by uelmuel1** [brandcolors/feedback#626]
- [x] *Brand Name*: DALIM SOFTWARE GmbH
- [x] *Brand Colors*: F8B222,1A171B,00C1FF
- [x] *Brand URL*: https://www.dalim.com/
- [x] *Where/how you found the brand colors*: Working at DALIM SOFTWARE GmbH

**Comment by galengidman** [comment]
Appreciate you taking the time to submit this. It's against BrandColors policy to add colors for agencies, so I'm going to have to pass.
