### ISSUE TITLE
Brand suggestion: Akamai

### ISSUE THREAD

**Issue by diarized** [brandcolors/feedback#629]
- [x] *Brand Name*: Akamai
- [x] *Brand Colors*: 0099CC,#FF9933
- [x] *Brand URL*: https://www.akamai.com/
- [x] *Where/how you found the brand colors*: Internal "Akamai Brand Identity Guidelines"

**Comment by dkhamsing** [comment]
Submitted brand `647` for review, thanks

**Comment by galengidman** [comment]
Published.
