### ISSUE TITLE
Rochester Institute of Technology

### ISSUE THREAD

**Issue by connorjan** [brandcolors/feedback#630]
- [x] *Brand Name*: Rochester Institute of Technology
- [x] *Brand Colors*: f36e21,513127
- [x] *Brand URL*: https://www.rit.edu/
- [x] *Where/how you found the brand colors*: Nice and easy: https://www.rit.edu/upub/graphic-standards

**Comment by dkhamsing** [comment]
Submitted brand `649` for review, thanks

**Comment by galengidman** [comment]
Published.
