### ISSUE TITLE
Brand Suggestion: Northwestern University

### ISSUE THREAD

**Issue by mbklein** [brandcolors/feedback#631]
- [x] *Brand Name*: Northwestern University
- [x] *Brand Colors*: 4E2A84,836EAA,401F68,B6ACD1,E4E0EE,342F2E,716C6B,BBB8B8,D8D6D6
- [x] *Brand URL*: http://www.northwestern.edu/brand/
- [x] *Where/how you found the brand colors*: http://www.northwestern.edu/brand/visual-identity/color/digital-colors.html

**Comment by dkhamsing** [comment]
Submitted brand `651` for review, thanks

**Comment by galengidman** [comment]
Published.
