### ISSUE TITLE
Brand Suggestion: PrestaShop

### ISSUE THREAD

**Issue by gnumax** [brandcolors/feedback#632]
- [ ] *Brand Name*: PrestaShop
- [ ] *Brand Colors*: DF0067,251B5B,25B9D7,FBBB22,68737F,BBBFC3
- [ ] *Brand URL*: https://www.prestashop.com
- [ ] *Where/how you found the brand colors*: https://www.prestashop.com/en/media-kit

**Comment by galengidman** [comment]
Published.
