### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by albycanepa** [brandcolors/feedback#634]
- [x] *Brand Name*: Javascript
- [x] *Brand Colors*: f7df1e,000000
- [ ] *Brand URL*:
- [x] *Where/how you found the brand colors*: wiki commons

**Comment by albycanepa** [comment]
This is unofficial as JS is a language not a brand but it can be useful consolidate Javascript image used around the web. Adding this to brandcolors library can be good to get the colour faster than everywhere else.

Source: https://commons.wikimedia.org/wiki/File:Unofficial_JavaScript_logo_2.svg

**Comment by dkhamsing** [comment]
@galengidman what do you think

**Comment by galengidman** [comment]
Makes sense to me. Published.
