### ISSUE TITLE
Brand suggestion: Polaroid

### ISSUE THREAD

**Issue by albycanepa** [brandcolors/feedback#636]
- [x] *Brand Name*: Polaroid
- [x] *Brand Colors*: f15e51,936fb0,1c94d2,12b6b3,6ec17b,a3ce5a,ffca13,f69323,959c8b
- [x] *Brand URL*: http://www.polaroid.com/
- [x] *Where/how you found the brand colors*: website logo

**Comment by galengidman** [comment]
Published.
