### ISSUE TITLE
Brand request: NZXT

### ISSUE THREAD

**Issue by ente3000** [brandcolors/feedback#641]
- [x] *Brand Name*: NZXT
- [x] *Brand Colors*: 51007A, DBE800, D0D3D4, 7C878E (also 000000 and FFFFFF)
- [x] *Brand URL*: https://www.nzxt.com
- [x] *Where/how you found the brand colors*: [Official branding page](https://www.nzxt.com/branding)

**Comment by galengidman** [comment]
Published.
