### ISSUE TITLE
Brand suggestion: Ninjas in Pyjamas

### ISSUE THREAD

**Issue by Kameeleonn** [brandcolors/feedback#643]
- [x] *Brand Name*: **Ninjas in Pyjamas**
- [x] *Brand Colors*: **a98c66**
- [x] *Brand URL*: **https://nip.gl**
- [x] *Where/how you found the brand colors*: **Brand Guideline https://www.dropbox.com/s/zc7fud5j0wcztlx/Xtrfy_NiP_Branguideline_20170915.pdf**

**Comment by galengidman** [comment]
Published.
