### ISSUE TITLE
Brand Suggestion: Contant Contact

### ISSUE THREAD

**Issue by manattweb** [brandcolors/feedback#644]
- [x] *Brand Name*: Constant Contact
- [x] *Brand Colors*: 5CABD4 (blue, main), f6b128 (orange)
- [x] *Brand URL*: https://www.constantcontact.com 
- [x] *Where/how you found the brand colors*: nav color of any internal page for blue, button color for orange

**Comment by dkhamsing** [comment]
Submitted brand `789 ` for review, thanks

**Comment by galengidman** [comment]
Published.
