### ISSUE TITLE
Brand Suggestion: SK8Tech

### ISSUE THREAD

**Issue by jacktator** [brandcolors/feedback#645]
- [x ] *Brand Name*: SK8Tech
- [ x] *Brand Colors*: 171c61(Blue), ffffff(White)
- [ x] *Brand URL*: https://sk8.tech
- [ x] *Where/how you found the brand colors*: I'm the owner of this startup. haha.

**Comment by galengidman** [comment]
Thanks for taking the time to submit. It's against BC policy to post agency colors, so I'll have to decline this.
