### ISSUE TITLE
Brand Suggestion: NS

### ISSUE THREAD

**Issue by interDist** [brandcolors/feedback#647]
- [x] *Brand Name*: NS
- [x] *Brand Colors*: 003082, ffc917
- [x] *Brand URL*: https://www.ns.nl
- [x] *Where/how you found the brand colors*: https://www.ns.nl/static/generic/2.19.0/images/nslogo.svg, https://www.ns.nl/static/generic/2.19.0/css/generic.min.css (`ns--tile-blue` and `ns--tile-yellow`)

**Comment by galengidman** [comment]
Published.
