### ISSUE TITLE
Brand Suggestion: Poczta Polska

### ISSUE THREAD

**Issue by interDist** [brandcolors/feedback#648]
- [X] *Brand Name*: Poczta Polska
- [X] *Brand Colors*: e71905, ffe500, ffffff
- [X] *Brand URL*: http://www.poczta-polska.pl
- [X] *Where/how you found the brand colors*: extracted from http://www.poczta-polska.pl/hermes/themes/poczta-polska/skin/logo.png

**Comment by galengidman** [comment]
Published.
