### ISSUE TITLE
Brand Suggestion: Avast

### ISSUE THREAD

**Issue by The-Crooked-Man** [brandcolors/feedback#652]
- [x] *Brand Name*: Avast
- [x] *Brand Colors*: ff7800, 2d364c, 6534ac, 0cb754, 000000, ffffff
- [x] *Brand URL*: https://www.avast.com/
- [x] *Where/how you found the brand colors*: From their Logo Manual (.pdf) -  https://press.avast.com/hubfs/media-materials/logos-guidelines/Avast/avast-logo-manual-web.pdf?t=1511892627076
and the green was colour-picked from their windows antivirus (on a flat button, no gradient).

**Comment by galengidman** [comment]
Published.
