### ISSUE TITLE
Brand Suggestion: AMP

### ISSUE THREAD

**Issue by bluemwhitew** [brandcolors/feedback#653]
- [x] *Brand Name*: Accelerated Mobile Pages (AMP)
- [x] *Brand Colors*: `#1c79c0`, `#0dd3ff`, `#0389ff`
- [x] *Brand URL*: https://www.ampproject.org
- [x] *Source*: https://www.ampproject.org/static/img/brand-guidelines.pdf

**Comment by galengidman** [comment]
Published.
