### ISSUE TITLE
Bella Sunshine Designs

### ISSUE THREAD

**Issue by GumbyUF** [brandcolors/feedback#655]
- [x] *Brand Name*: Bella Sunshine Designs
- [x] *Brand Colors*: FF8B0F,E84F90,00BBBB,FDCA10,F9DFEB,DAEAFF,B6EBA7,FEE6C3,83B9FD,0D214B
- [x] *Brand URL*: bellasunshinedesigns.com
- [x] *Where/how you found the brand colors*: Style Guide https://github.com/bellasunshinedesigns/Style-Guide/blob/master/BSD_StyleGuide.pdf

**Comment by galengidman** [comment]
I appreciate you taking the time to submit this, and it's a really nice palette. I'm going to turn it down for now — I'm not sure the brand has grown to a place where it's ready to be included on the site.
