### ISSUE TITLE
Talloo

### ISSUE THREAD

**Issue by georgeseybold** [brandcolors/feedback#656]
- [x] *Brand Name*: Talloo
- [x] *Brand Colors*: DD0000, 000000, F9F9F9, EEEEEE
- [x] *Brand URL*: https://talloo.com
- [x] *Where/how you found the brand colors*: I am the brand manager.

**Comment by galengidman** [comment]
I appreciate you taking the time to submit. I'm not sure Talloo is yet at the place where it's well-known enough to be added to BrandColors, but if I see it growing in the future, I'll be happy to add.
