### ISSUE TITLE
Internet Society

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#664]
- [X] *Brand Name*: Internet Society
- [X] *Brand Colors*: 0033a0, 009fd9, 001489, 485cc7, 63666a, 94999b:
- [X] *Brand URL*:http://internetsociety.ong
- [X] *Where/how you found the brand colors*:http://internetsociety.ong/sites/default/files/InternetSociety-VisualGuidelines-Logo-201109.pdf

**Comment by galengidman** [comment]
Published.
