### ISSUE TITLE
University of Rochester

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#665]
- [x] *Brand Name*: University of Rochester
- [x] *Brand Colors*: ffd100, 003b71
- [x] *Brand URL*: https://www.rochester.edu/
- [x] *Where/how you found the brand colors*: Listed on page 15 of [U of R's Identity Guide](https://www.rochester.edu/creativeservices/identityguide_2017.pdf). Further info at [the Creative Services dept](https://www.rochester.edu/creativeservices/).

**Comment by galengidman** [comment]
Published.
