### ISSUE TITLE
Wikimedia Foundation

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#666]
- [x] *Brand Name*: Wikimedia Foundation
- [x] *Brand Colors*: 339966, 0063bf, 990000
- [x] *Brand URL*: https://www.wikimedia.org/
- [x] *Where/how you found the brand colors*: [Brand guidelines](https://meta.wikimedia.org/wiki/Brand#Using_the_Wikimedia_colors)

**Comment by galengidman** [comment]
Published.
