### ISSUE TITLE
Y Combinator

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#667]
- [x] *Brand Name*: Y Combinator
- [x] *Brand Colors*: ff4000, ffffff
- [x] *Brand URL*: https://www.ycombinator.com/
- [x] *Where/how you found the brand colors*: Pulled from the .eps file linked on [their press page](https://www.ycombinator.com/press/#assets)

Note: Y Combinator shares its branding with Hacker News (https://news.ycombinator.com/), so searching for Hacker News should also return the Y Combinator branding (it could simply be listed as "Y Combinator / Hacker News").

**Comment by galengidman** [comment]
Published.
