### ISSUE TITLE
University of Cincinnati

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#668]
- [x] *Brand Name*: University of Cincinnati
- [x] *Brand Colors*: e00122, 000000, ffffff
- [x] *Brand URL*: https://www.uc.edu/
- [x] *Where/how you found the brand colors*: [Brand Guide](https://www.uc.edu/ucomm/brand.html) (color codes are on page 1 of the Quick Guide pdf)

**Comment by galengidman** [comment]
Published.
