### ISSUE TITLE
Duke University

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#670]
- [x] *Brand Name*: Duke University
- [x] *Brand Colors*: 001a57, 003366
- [x] *Brand URL*: https://www.duke.edu/
- [x] *Where/how you found the brand colors*: [Color Palette on Duke Style Guide](https://styleguide.duke.edu/color-palette/)

Note: The style guide lists a lot of choices for secondary colors, but I worry there's so many (particularly so many blues) that it'd be confusing to include them all.

**Comment by galengidman** [comment]
Published.
