### ISSUE TITLE
FiveThirtyEight

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#671]
- [x] *Brand Name*: FiveThirtyEight
- [x] *Brand Colors*: ed713a, 000000, ffffff
- [x] *Brand URL*: http://fivethirtyeight.com/
- [x] *Where/how you found the brand colors*: Pulled from [their logo](https://s0.wp.com/wp-content/themes/vip/espn-fivethirtyeight/assets/images/logo-fox-head-color.svg) on their website (that's the logo that appears in the navigation bar when you scroll down any page on their site)

**Comment by galengidman** [comment]
Published.
