### ISSUE TITLE
Major League Baseball

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#673]
- [x] *Brand Name*: Major League Baseball (MLB)
- [x] *Brand Colors*: 000088, cc0000, ffffff
- [x] *Brand URL*: https://www.mlb.com/
- [x] *Where/how you found the brand colors*: From the [MLB.com logo on their website](https://www.mlbstatic.com/mlb.com/builds/site-core/b107ebf561cfb7be3b527bf10ec997594884a1a3_1515618998/images/logos/url/mlb.svg) (I also made sure the colors are the same for the non-".com" version of their logo, which I found [on Wikipedia](https://en.wikipedia.org/wiki/Major_League_Baseball#/media/File:Major_League_Baseball_logo.svg))

**Comment by galengidman** [comment]
Published.
