### ISSUE TITLE
Plex

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#674]
- [x] *Brand Name*: Plex
- [x] *Brand Colors*: e5a00d, 282a2d, ffffff
- [x] *Brand URL*: https://www.plex.tv/
- [x] *Where/how you found the brand colors*: [Color Palettes](http://brand.plex.tv/d/qxmJ3odkK0fj/plex-style-guide#/basics/color-palettes) on their branding website

**Comment by galengidman** [comment]
Published.
