### ISSUE TITLE
Xavier University

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#675]
- [x] *Brand Name*: Xavier University
- [x] *Brand Colors*: 0c2340, 9ea2a2, 0099cc
- [x] *Brand URL*: https://www.xavier.edu/
- [x] *Where/how you found the brand colors*: [The Xavier Brand: Design Elements](https://www.xavier.edu/brand/design-elements.cfm)

**Comment by galengidman** [comment]
Published.
