### ISSUE TITLE
Ars Technica

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#676]
- [x] *Brand Name*: Ars Technica
- [x] *Brand Colors*: ff4e00, 030303, 01cd74
- [x] *Brand URL*: https://arstechnica.com/
- [x] *Where/how you found the brand colors*: Pulled from various parts of their website:
  - ff4e00 is from the SVG logo in the header and the color of most links on the site
  - 030303 is the background color of the header and the footer
  - 01cd74 is used for text in the header, page footer, and misc stuff in articles

**Comment by galengidman** [comment]
Published.
