### ISSUE TITLE
Humble Bundle

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#678]
- [x] *Brand Name*: Humble Bundle
- [x] *Brand Colors*: cb2729, bc1f24
- [x] *Brand URL*: https://www.humblebundle.com/
- [x] *Where/how you found the brand colors*: Extracted from various SVG logos found [here](https://support.humblebundle.com/hc/en-us/articles/202742060-Bundle-Logos)

**Comment by galengidman** [comment]
Published.
