### ISSUE TITLE
CNN

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#679]
- [x] *Brand Name*: CNN (Cable News Network)
- [x] *Brand Colors*: cc0000, 000000, ffffff, 282828, 464646
- [x] *Brand URL*: https://www.cnn.com/
- [x] *Where/how you found the brand colors*: pages 9-10 of [Logo Usage Guide](https://developer.cnn.com/files/Logo_Usage_Guide_JANUARY2015.pdf)

**Comment by galengidman** [comment]
Published.
