### ISSUE TITLE
Mojang

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#681]
- [x] *Brand Name*: Mojang
- [x] *Brand Colors*: db1f29, 000000
- [x] *Brand URL*: https://mojang.com/
- [x] *Where/how you found the brand colors*: Extract from [SVG logo on their website](https://mojang.com/assets/mojang-logo-b5980396e697fa0256589e67b6f8dbcb7caabc6dc8ef439ddff8c89667fd3c37.svg)

**Comment by galengidman** [comment]
Published.
