### ISSUE TITLE
Wake Forest University

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#682]
- [x] *Brand Name*: Wake Forest University
- [x] *Brand Colors*: 9E7E38, 000000, 82231C, 511536, 443E67, 375669, 456525, 59786C, 3D3C1D, 625750
- [x] *Brand URL*: http://www.wfu.edu/
- [x] *Where/how you found the brand colors*: [Identity Standards: Colors and Paper Stock](http://identitystandards.wfu.edu/design-guidelines/colors-paper-stock/)

**Comment by galengidman** [comment]
Published.
