### ISSUE TITLE
University of North Carolina

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#683]
- [x] *Brand Name*: University of North Carolina (UNC)
- [x] *Brand Colors*: 4B9CD3, 007FAE, 13294B, E1E1E1, 767676, 151515
- [x] *Brand URL*: https://www.unc.edu/
- [x] *Where/how you found the brand colors*: [Carolina Blue and Color Guidelines](https://identity.unc.edu/colors/)

**Comment by galengidman** [comment]
Published.
