### ISSUE TITLE
Clemson University

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#684]
- [x] *Brand Name*: Clemson University
- [x] *Brand Colors*: F66733, 522D80, FFFFFF, D4C99E, 685C53, A25016, 562E19, 86898C, F9E498, 566127, 3A4958, B5C327, 109DC0, 000000
- [x] *Brand URL*: https://www.clemson.edu
- [x] *Where/how you found the brand colors*: [Color Palette](https://www.clemson.edu/brand/guide/color.html) on Clemson's website

**Comment by galengidman** [comment]
Published.

**Comment by oxguy3** [comment]
Thanks for publishing all these. Btw, looks like Clemson got added twice.

**Comment by galengidman** [comment]
no problem - thanks for submitting them. I've fixed the dupe Clemson.
