### ISSUE TITLE
University of Dayton

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#685]
- [x] *Brand Name*: University of Dayton
- [x] *Brand Colors*: CE1141, 004B8D, 000000, FAF2F3, D1CDB8, FFFFFF, CF0A2C, 0082CA, 199051, E76829, FFDD00
- [x] *Brand URL*: https://udayton.edu/
- [x] *Where/how you found the brand colors*: [Brand Colors](https://udayton.edu/brand/colors.php)

**Comment by galengidman** [comment]
Published.
