### ISSUE TITLE
Hayden Schiff 070809.us

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#687]
Brand Name: Hayden Schiff
Brand Colors: 070809
 Brand URL: https://oxguy3.github.io/#home
 Where/how you found the brand colors: https://plus.google.com/u/0/+a5a0a9ie/posts/MdEaLY5MLvb

**Comment by oxguy3** [comment]
Um what? Why am I a brand? What is that link??

**Comment by galengidman** [comment]
@RachelWatson9b13a9 

I received your email a few days ago and from what I can tell, your idea is that every internet user would have their own assigned hex color that would be used as their fingerprint on the internet. Everything they did or posted would be connected to that color. This color could somehow be used as a means of cybersecurity? And they would have localized domains of the hex code — e.g.: ff0000.us.

I'm not sure I totally understand your idea, but I can tell you that BrandColors is not the place I want to host this data. Please do not submit brands for random individuals.

Not that it's something I have authority over, but I'll bet they do not want you to post ID cards of a society that doesn't exist with their name, photo, and web address to Google+ either. It's creepy.
