### ISSUE TITLE
Oregon State University

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#688]
- [x] *Brand Name*: Oregon State University
- [x] *Brand Colors*: DC4405, 000000, FFFFFF
- [x] *Brand URL*: http://oregonstate.edu/
- [x] *Where/how you found the brand colors*: [The Oregon State Brand: Colors](http://communications.oregonstate.edu/brand-guide/visual-identity/colors)

**Comment by galengidman** [comment]
Published.
