### ISSUE TITLE
State University of New York at Albany

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#689]
- [x] *Brand Name*: State University of New York at Albany (University at Albany, SUNY Albany)
- [x] *Brand Colors*: 46166b, eeb211, 006c68, 97a4af
- [x] *Brand URL*: https://www.albany.edu/
- [x] *Where/how you found the brand colors*: [Graphic Identity Manual](https://www.albany.edu/communicationsmarketing/files/Graphic-Manual-2017.pdf), page 5
  - The primary purple color code is listed incorrectly in the manual as "46166"; I converted the RGB values to get the correct "46166b"

**Comment by galengidman** [comment]
Published.
