### ISSUE TITLE
State University of New York at Buffalo

### ISSUE THREAD

**Issue by oxguy3** [brandcolors/feedback#690]
- [x] *Brand Name*: State University of New York at Buffalo (University at Buffalo, SUNY Buffalo)
- [x] *Brand Colors*: 005bbb, ffffff, e56a54, ffc72c, ebec00, 00a69c, 990000, ad841f, 6da04b, 006570, 2f9fd0, 002f56, e4e4e4, 666666
- [x] *Brand URL*: http://www.buffalo.edu/
- [x] *Where/how you found the brand colors*: [Identity and Brand: Color Palette](http://www.buffalo.edu/brand/creative/color/color-palette.html)

**Comment by galengidman** [comment]
Published.
