### ISSUE TITLE
Flag of the United States

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#691]
- [X] *Brand Name*:Flag of the United States
- [X] *Brand Colors*:b22234,ffffff,3c3b6e
- [X] *Brand URL*:https://www.dhs.gov/
- [X] *Where/how you found the brand colors*:https://en.wikipedia.org/wiki/Flag_of_the_United_States

**Comment by dkhamsing** [comment]
@galengidman what do you think of this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
