### ISSUE TITLE
Wikimedia

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#697]
- [x] *Brand Name*:Wikimedia
- [x] *Brand Colors*:990000, 006699, 339966, 484848, 666666.
- [x] *Brand URL*:https://www.wikimedia.org/
- [x] *Where/how you found the brand colors*:https://wikimediafoundation.org/wiki/Archived/Wikimedia_visual_identity_guidelines

**Comment by RachelWatson9b13a9** [comment]
https://livestream.com/internetsociety/wikidaynyc

**Comment by oxguy3** [comment]
Duplicate of #666
