### ISSUE TITLE
Massachusetts Institute of Technology

### ISSUE THREAD

**Issue by nwLSteam** [brandcolors/feedback#698]
- [X] *Brand Name*: Massachusetts Institute of Technology
- [X] *Brand Colors*: a31f34, 8a8b8c, c2c0bf
- [X] *Brand URL*: http://web.mit.edu/
- [X] *Where/how you found the brand colors*: http://web.mit.edu/graphicidentity/colors.html

**Comment by galengidman** [comment]
Published.
