### ISSUE TITLE
SoapUI

### ISSUE THREAD

**Issue by pjstevens10** [brandcolors/feedback#699]
- [x] *Brand Name*: SoapUI
- [x] *Brand Colors*: 6cb33f, ffffff, 4a494d
- [x] *Brand URL*: https://www.soapui.org/
- [x] *Where/how you found the brand colors*: I work for SmartBear, the company behind SoapUI.

**Comment by galengidman** [comment]
Published.

**Comment by pjstevens10** [comment]
Thanks, @galengidman. Cheers!
