### ISSUE TITLE
Knight Foundation

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#700]
- [x] *Brand Name*:Knight Foundation
- [x] *Brand Colors*:000000, FFFFFF
- [x] *Brand URL*:https://knightfoundation.org/
- [x] *Where/how you found the brand colors*:
https://knight.app.box.com/s/r4t8h8xazdlw6ehxdqk01nvoqsq0s1tz

**Comment by galengidman** [comment]
Published.
