### ISSUE TITLE
Brand Suggestion: InVision

### ISSUE THREAD

**Issue by bluemwhitew** [brandcolors/feedback#701]
- [x] **Brand Name**: InVision
- [x] **Brand Colors**: `#ff3366`, `#252b33`, `#2f7bbd`, `#323a45`, `#8a959e`, `#d4d7da`, `#e9ebec`
- [x] **Brand URL**: https://www.invisionapp.com
- [x] **Source**: https://projects.invisionapp.com/boards/BX4P1DY5H46R

**Comment by dkhamsing** [comment]
Submitted brand `880 ` for review, thanks

**Comment by galengidman** [comment]
Published.
