### ISSUE TITLE
Brand Suggestion: PeoplePerHour (PPH)

### ISSUE THREAD

**Issue by bluemwhitew** [brandcolors/feedback#702]
- [x] **Brand Name**: PeoplePerHour
- [x] **Brand Colors**: `#ee751d`, `#fefefe`, `#555555`
- [x] **Brand URL**: https://www.peopleperhour.com
- [x] **Source**: http://blog.peopleperhour.com/press_kit.zip

**Comment by galengidman** [comment]
Published.
