### ISSUE TITLE
WhatsBroadcast

### ISSUE THREAD

**Issue by spurznet** [brandcolors/feedback#706]
- [ ] *Brand Name*: WhatsBroadcast
- [ ] *Brand Colors*: #4AAE20, #6CC751, #225F1E, #F8CC07, #FF9300, #E44436, #CD3292, #37AEF3, #0076BA, #005888, #8732CD, #33482C
- [ ] *Brand URL*: https://www.whatsbroadcast.com/
- [ ] *Where/how you found the brand colors*: https://www.whatsbroadcast.com/de/brand-ressources/ (also, I designed the new brand design)

**Comment by galengidman** [comment]
https://brandcolors.net/b/whatsbroadcast
