### ISSUE TITLE
Brand Suggestion: Ramotion

### ISSUE THREAD

**Issue by alexmikhnev** [brandcolors/feedback#765]
- [x] *Brand Name*: Ramotion
- [x] *Brand Colors*: 1863dc,ffffff
- [x] *Brand URL*: https://www.ramotion.com
- [x] *Where/how you found the brand colors*: https://www.behance.net/gallery/35613259/Ramotion-Branding

**Comment by galengidman** [comment]
Thanks for taking the time to submit. It's a BC policy not to publish colors of design agencies though, so I'll have pass over this one. All the best.
