### ISSUE TITLE
Threema

### ISSUE THREAD

**Issue by dominicplet** [brandcolors/feedback#826]
- [X] *Brand Name*: Threema
- [X] *Brand Colors*: 3FE669, 7491E8, 0F224D
- [X] *Brand URL*: https://threema.ch/en
- [X] *Where/how you found the brand colors*: In the SVG logo files downloaded from the [Threema Press Material](https://threema.ch/en/press) under the chapter "Graphics".

**Comment by skowie** [comment]
For information: Threema is a popular secure messenger in Central Europe. In the area it is the #1 ranking app in the App Store under Social Networking. Its badge or a link to a users "Threema ID" is getting more and more popular on some personal websites and in pre-made themes, so it would be awesome to quickly find the fitting color on brandcolors.
