### ISSUE TITLE
Your website's background

### ISSUE THREAD

**Issue by runxel** [brandcolors/feedback#828]
Hey there!

Your website's background is missing 😉 

![bc](https://user-images.githubusercontent.com/2277182/71200407-42d74900-2298-11ea-8d12-c602dee4f049.png)

---

(Explanation: Not everybody has its natural color set to white. Maybe you want to also investigate the possibility of a stylesheet for users who [prefer a dark color scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).)

**Comment by BobaWebDev** [comment]
@runxel 

Just checking to see if the issue still happens, we made an adjustment a while ago that should have fixed that issue.

**Comment by runxel** [comment]
Looks better now, thanks alot @BobaWebDev! :)
