### ISSUE TITLE
CSS: no background color

### ISSUE THREAD

**Issue by runxel** [brandcolors/feedback#838]
Hey there!

Would be nice if you could make your css a bit saner by adding a background color!:

![bgcol](https://user-images.githubusercontent.com/2277182/74662123-97fce180-5199-11ea-9855-824d8172def9.jpg)

Thanks for considering :)

**Comment by grimsi** [comment]
Duplicate of #828 ?

**Comment by runxel** [comment]
> Duplicate of #828 ?

Haha, daaamn. Sorry! Seems my mind's not the best. Mea culpa for this dup.
