### ISSUE TITLE
Booqable

### ISSUE THREAD

**Issue by jeffreyvanderveer** [brandcolors/feedback#846]
- [x] *Brand Name*: Booqable
- [x] *Brand Colors*: #2b80ff
- [x] *Brand URL*: https://booqable.com/
- [x] *Where/how you found the brand colors*: I work for the Booqable marketing team and know the exact brand colors.

**Comment by jeffreyvanderveer** [comment]
@galengidman Hi Galen, please let me know if there's anything else you need from me.

**Comment by galengidman** [comment]
Hi @jeffreyvanderveer,

I sold BrandColors in February of last year and no longer own or manage the site. I'm not sure if the new owners are still making updates, but it's not something I can help with anymore.

Thanks for taking the time to contribute this!

**Comment by FancyThemes** [comment]
Published.
