### ISSUE TITLE
Nintendo

### ISSUE THREAD

**Issue by visiblyisabelle** [brandcolors/feedback#854]
- [x] *Brand Name*: Nintendo
- [x] *Brand Colors*: e60012, ffffff, 8c8c8c
- [x] *Brand URL*: https://nintendo.com/
- [x] *Where/how you found the brand colors*: From logo on https://www.nintendo.com/ and Wikipedia https://en.wikipedia.org/wiki/Nintendo#Logos

**Comment by alexanderkladov** [comment]
Where did you get the **e7000a** color? I think it's a bit off - it should be **e60012** instead. Based on their official logo badge background color on [their website](https://nintendo.com/). If you open Chrome developer toolbar and look for the element with `.logo-nintendo` class, it has `background-color: #E60012;` applied in CSS.

**Comment by visiblyisabelle** [comment]
You're right, updated. Not sure what I did but the correct colour is definitely #e60012

**Comment by FancyThemes** [comment]
Published.
