### ISSUE TITLE
Brand Request: LoginRadius

### ISSUE THREAD

**Issue by aman-agrwl-zz** [brandcolors/feedback#870]
- [x] *Brand Name*: LoginRadius
- [x] *Brand Colors*:  008ecf, 09263c, 020b13, e3f1f8, 073857
- [x] *Brand URL*: https://www.loginradius.com/
- [x] *Where/how you found the brand colors*: I am the employee, found this from our internal design docs

**Comment by FancyThemes** [comment]
Added.

**Comment by aman-agrwl-zz** [comment]
@FancyThemes Thanks for merging the PR. 

But I just wanted to mention that, you have mentioned the organization name incorrect. There is no space between `Login` and `Radius`. Please keep them as a single word `LoginRadius`.

**Comment by FancyThemes** [comment]
@aman-agrwl Fixed.
