### ISSUE TITLE
Brand Update: Twitch

### ISSUE THREAD

**Issue by Glaived** [brandcolors/feedback#873]
- [x] **Brand Name**: Twitch
- [x] **Brand Colors**: `#9146FF`, `#000000`, `#F0F0FF`
- [x] **Brand URL**: https://twitch.tv
- [x] **Where/how you found the brand colors**: https://brand.twitch.tv/brand/

**Comment by FancyThemes** [comment]
Added.

**Comment by Glaived** [comment]
@FancyThemes Need to remove https://brandcolors.net/b/twitch-tv i think ?

**Comment by FancyThemes** [comment]
@Glaived Fixed. Thanks for pointing it out.
