### ISSUE TITLE
Yummly Social Network

### ISSUE THREAD

**Issue by geoffreycrofte** [brandcolors/feedback#874]
- [x] *Brand Name*: Yummly
- [x] *Brand Colors*: #E16120, #3a9691, #363533
- [x] *Brand URL*: https://www.yummly.com/
- [x] *Where/how you found the brand colors*: Main CSS variables + Official Logo color (SVG declared hexa)

**Comment by FancyThemes** [comment]
hey @geoffreycrofte added.
