### ISSUE TITLE
Add NHS - National Health Service 

### ISSUE THREAD

**Issue by janwyl1** [brandcolors/feedback#875]
- [x] *Brand Name*: NHS 
- [x] *Brand Colors*: #005EB8, #FFFFFF
- [x] *Brand URL*: https://www.england.nhs.uk/nhsidentity/identity-guidelines/colours/
- [x] *Where/how you found the brand colors*: NHS Brand Identity Guidelines

**Comment by FancyThemes** [comment]
@janwyl1 Added.
