### ISSUE TITLE
Add GlaxoSmithKline

### ISSUE THREAD

**Issue by janwyl1** [brandcolors/feedback#876]
- [x] *Brand Name*: GlaxoSmithKline
- [x] *Brand Colors*: #F36F21, #72635C, #ACA6A2, #FFFFFF
- [x] *Brand URL*: https://cz.gsk.com/media/510676/gsk-new-brand-rules2013.pdf
- [x] *Where/how you found the brand colors*: Our Look and Feel Visual Guidelines - Page 73 (Colors are in CMYK but I converted them to hex using Illustrator - hope thats ok)

**Comment by FancyThemes** [comment]
Added.
