### ISSUE TITLE
Rochester Institute of Technology

### ISSUE THREAD

**Issue by Andrew-Burch** [brandcolors/feedback#882]
- [Rochester Institute of Technology] *Brand Name*:
- [#F76902, #FFFFFF, #000000] *Brand Colors*:
- [https://www.rit.edu/] *Brand URL*:
- [https://www.rit.edu/marketing/brandportal/brand-elements/colors] *Where/how you found the brand colors*:

**Comment by FancyThemes** [comment]
Added!
