### ISSUE TITLE
Overwolf

### ISSUE THREAD

**Issue by derJuba007** [brandcolors/feedback#886]
- [x] *Brand Name*: Overwolf
- [x] *Brand Colors*: 161326, 484266, 958FB2, F4F2FF, E6004C
- [x] *Brand URL*: [https://www.overwolf.com/](https://www.overwolf.com/)
- [x] *Where/how you found the brand colors*: [https://www.overwolf.com/brand-guidelines](https://www.overwolf.com/brand-guidelines)

**Comment by FancyThemes** [comment]
Added
