### ISSUE TITLE
Michigan State University

### ISSUE THREAD

**Issue by owebboy** [brandcolors/feedback#887]
- [x] *Brand Name*: Michigan State University
- [x] *Brand Colors*: 18453b, 0db14b, 97a2a2, f08521, 008183, 909ab7, 535054, d1de3f, e8d9b5, c89a58, 94ae4a, 6e005f, cb5a28
- [x] *Brand URL*: https://brand.msu.edu/design-visual/index.html#color
- [x] *Where/how you found the brand colors*: I am both a student and a web developer at MSU

**Comment by FancyThemes** [comment]
Added.
