### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by derJuba007** [brandcolors/feedback#890]
- [x] *Brand Name*: Zoom
- [x] *Brand Colors*:  2d8cff `primary`, f26d21
- [x] *Brand URL*: https://zoom.us/
- [x] *Where/how you found the brand colors*: https://zoom.us/brandguidelines

**Comment by FancyThemes** [comment]
Added.

**Comment by derJuba007** [comment]
You accidentally added a "a" behind the color code. It is `2d8cffa` and should be `2d8cff`

**Comment by FancyThemes** [comment]
hey @derJuba007 thanks for pointing that out. fixed!
