### ISSUE TITLE
Qonto Brand Color

### ISSUE THREAD

**Issue by geoffreycrofte** [brandcolors/feedback#893]
- [x] *Brand Name*: Qonto
- [x] *Brand Colors*: 6B5AED, 262A3E, FAFAFC, 63EBE4
- [x] *Brand URL*: https://qonto.com/en
- [x] *Where/how you found the brand colors*: Their media/press kit [here](https://projects.invisionapp.com/boards/F72NQW5WTE3AN#/4467173)

BTW, is this project still alive? I see a lot of PRs in there with no validation.

**Comment by FancyThemes** [comment]
@geoffreycrofte Yep, still alive. Added!

**Comment by geoffreycrofte** [comment]
Thank you :)
