### ISSUE TITLE
Great Western Railway

### ISSUE THREAD

**Issue by edwardcallow** [brandcolors/feedback#894]
- [x] *Brand Name*: Great Western Railway (GWR)
- [x] *Brand Colors*: 0b2d27,000000,ffffff
- [x] *Brand URL*: www.gwr.com
- [x] *Where/how you found the brand colors*: Page 780 of https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/925399/great-western-rail-franchise-agreement.pdf

**Comment by FancyThemes** [comment]
Added!
