### ISSUE TITLE
Royal Central School of Speech and Drama

### ISSUE THREAD

**Issue by edwardcallow** [brandcolors/feedback#895]
- [x] *Brand Name*: Royal Central School of Speech and Drama
- [x] *Brand Colors*: 1b5692,c32128,43a756,999999,de8a3d,74a2d7,f0c33b,9fc54d
- [x] *Brand URL*: www.cssd.ac.uk
- [x] *Where/how you found the brand colors*: I work at Central. Taken from internal brand guidelines.

**Comment by FancyThemes** [comment]
Added!
