### ISSUE TITLE
Additional brand - Goethe-Institut

### ISSUE THREAD

**Issue by EttlChristian** [brandcolors/feedback#898]
- [x] *Brand Name*: Goethe-Institut
- [x] *Brand Colors*: a5c500,810061,303600,ec6400,d4c78c,5ec6f2,003468,4b1702,717a83
- [x] *Brand URL*: www.goethe.de
- [x] *Where/how you found the brand colors*: [Designguidelines_en.pdf](https://github.com/brandcolors/feedback/files/6245875/Designguidelines_en.pdf) Page 32+33

**Comment by FancyThemes** [comment]
@EttlChristian Added.
