### ISSUE TITLE
AIESEC 

### ISSUE THREAD

**Issue by hambergerpls** [brandcolors/feedback#901]
There was a recent 2021 update for #660

- [x] *Brand Name*: AIESEC
- [x] *Brand Colors*: 037ef3, f85a40, **_00c16e_**, **_0cb9c1_**, f48924, ffc845, 52565e, caccd1, f3f4f7, **_7552cc_**
- [x] *Brand URL*: ![aiesec.org](aiesec.org)
- [x] *Where/how you found the brand colors*: Executive of AIESEC

![image](https://user-images.githubusercontent.com/11707368/117271347-a9103c00-ae8c-11eb-83e9-3fa6f73eae61.png)

**Comment by FancyThemes** [comment]
@hambergerpls thanks, updated.
