### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by SjorsHartwijk** [brandcolors/feedback#903]
- [X] *Brand Name*: Facebook
- [X] *Brand Colors*: #1877f2
- [X] *Brand URL*: https://en.facebookbrand.com/facebookapp/
- [X] *Where/how you found the brand colors*:
Inspect element on the first H2
rgb(24,119,242) == #1877f2

**Comment by FancyThemes** [comment]
@SjorsHartwijk Updated.
