### ISSUE TITLE
CNBC

### ISSUE THREAD

**Issue by diegobot1977** [brandcolors/feedback#905]
- [x] *Brand Name*: CNBC
- [x] *Brand Colors*: #292526, #cd004b, #f37023, #fcb711, #0eb24e, #0087d2, #6561ac
- [x] *Brand URL*: https://www.cnbc.com/
- [x] *Where/how you found the brand colors*: I just found in the Wikimedia Commons file, https://commons.wikimedia.org/wiki/File:CNBC_logo.svg, as we just picked multiple colors in this logo.

**Comment by FancyThemes** [comment]
@diegobot1977 Added.
