### ISSUE TITLE
Discord (update)

### ISSUE THREAD

**Issue by vimaexd** [brandcolors/feedback#907]
- [x] *Brand Name*:
Discord (https://discord.com)
They've recently rebranded and updated their brand colors

- [x] *Brand Colors*:
5865F2,57F287,FEE75C,EB459E,ED4245,FFFFFF,000000,2c2f33,23272a

- [x] *Brand URL*:
https://discord.com/branding

- [x] *Where/how you found the brand colors*:
By visiting https://discord.com/branding and scrolling down to the "Colors" section
Two of the colors are no longer included in the website but were previously there are still used in the Discord app itself (namely 2c2f33 and 23272a)

**Comment by FancyThemes** [comment]
Updated -- https://brandcolors.net/b/discord
