### ISSUE TITLE
Xero

### ISSUE THREAD

**Issue by SmolSoftBoi** [brandcolors/feedback#914]
- [x] *Brand Name*: Xero
- [x] *Brand Colors*: Blue: `#06B3E8`, Black: `#000000`, White: `#FFFFFF`, Grey: `#7A7E85`
- [x] *Brand URL*: [xero.com](https://xero.com)
- [x] *Where/how you found the brand colors*: [Xero developer and app partner brand guidelines](https://developer.xero.com/static/otherfiles/xero-app-partner-brand-guidelines.pdf)

**Comment by FancyThemes** [comment]
@SmolSoftBoi Added.
