### ISSUE TITLE
Michigan State University Update

### ISSUE THREAD

**Issue by owebboy** [brandcolors/feedback#918]
- [x] *Brand Name*: Michigan State University
- [x] *Brand Colors*: 18443b,ffffff,000000,008208,7bbd00,0b9a6d
- [x] *Brand URL*:https://msu.edu/
- [x] *Where/how you found the brand colors*:https://brand.msu.edu/visual/color-palette

**Comment by FancyThemes** [comment]
Updated - https://brandcolors.net/b/msu
