### ISSUE TITLE
DuckDuckGo

### ISSUE THREAD

**Issue by Ghas95** [brandcolors/feedback#921]
- [x] *Brand Name*: DuckDuckGo
- [x] *Brand Colors*: e37151, de5833, ffffff, e5e5e5, 5b9e4d, e37151, 4495d4
- [x] *Brand URL*: https://duckduckgo.com/
- [x] *Where/how you found the brand colors*: https://duckduckgo.com/styleguide

**Comment by FancyThemes** [comment]
Added -- https://brandcolors.net/b/duckduckgo
