### ISSUE TITLE
LinkedIn Colors are out of date

### ISSUE THREAD

**Issue by stupac14** [brandcolors/feedback#930]
- [x] *Brand Name*: LinkedIn
- [x] *Brand Colors*: 0a66c2,83941f,e7a33e,f5987e,56687a,004182,44712e,915907,b24020,38434f,dce6f1,d7ebce,fce2ba,fadfd8,e9e5df,fdfaf5

- [x] *Brand URL*: https://www.linkedin.com/
- [x] *Where/how you found the brand colors*: I am a designer working with a ad agency who are contracted with LinkedIn. So I have current brand guidelines which have 16 colours (primary, dark, light and a single off white)
- ![Colours](https://user-images.githubusercontent.com/75731528/160635078-af841be8-99f7-47a6-8d42-4ce5ebbbc1d2.png)

**Comment by FancyThemes** [comment]
Fixed. Thanks for the heads up.
