### ISSUE TITLE
Comcast Brand Colors

### ISSUE THREAD

**Issue by wongstephen** [brandcolors/feedback#931]
- [Xfinity] *Brand Name*:
- [ 6138F5, 1F69FF, 008558, FFAA00, E64F00, E6004D] *Brand Colors*:
- [xfinity.com] *Brand,  URL*:
- [I got the brand guide. This is for Comcast's sub-brand Xfinity] *Where/how you found the brand colors*:

**Comment by FancyThemes** [comment]
Added.
