### ISSUE TITLE
MasterCard Colours Update - 1 January 2021

### ISSUE THREAD

**Issue by nicolas-giuristante** [brandcolors/feedback#949]
- [x] *Brand Name*: MasterCard
- [x] *Brand Colors*: EB001B,FF5F00,F79E1B
- [x] *Brand URL*: https://brand.mastercard.com/brandcenter/branding-requirements/mastercard.html#digital-payments
- [x] *Where/how you found the brand colors*: In the branding guidelines, under the accordion "Color Specifications"

<img width="629" alt="Screenshot 2023-03-03 at 17 07 54" src="https://user-images.githubusercontent.com/12054707/222838890-57b0619c-2282-4612-8663-8c3bcd23ed3f.png">

**Comment by FancyThemes** [comment]
@nicolas-giuristante Updated.
